USE QLPHONGKHAM_CSDLNC; 
GO

-- xem danh sách cuộc hẹn
CREATE OR ALTER PROCEDURE XEM_DS_CUOCHEN
AS
BEGIN
	SELECT * FROM CUOCHEN
END;
GO

EXEC XEM_DS_CUOCHEN
GO
-- tạo cuộc hẹn
CREATE OR ALTER PROCEDURE TAO_CUOCHEN
	@ID_BENHNHAN INT,
	@ID_NHASI INT,
	@ID_PHONGKHAM INT,
	@THOI_GIAN DATETIME,
	@GHICHU NVARCHAR(50),
	@TINHTRANG NVARCHAR(11)
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM BENHNHAN WHERE ID_BENHNHAN = @ID_BENHNHAN)
	BEGIN
		RAISERROR(N'BỆNH NHÂN KO TỒN TẠI', 16, 1)
		RETURN;
	END;

	INSERT INTO CUOCHEN(ID_BENHNHAN, ID_NHASI, ID_PHONGKHAM, THOIGIAN, GHICHU, TINHTRANG)
	VALUES (@ID_BENHNHAN, @ID_NHASI, @ID_PHONGKHAM, @THOI_GIAN, @GHICHU, @TINHTRANG)
END;
GO
EXEC TIM_NHASI_RANH 1, '2023-12-01 8:00'
EXEC TAO_CUOCHEN 1, 1, 1, '2023-12-01 8:30', '', N'Mới'
SELECT * FROM CUOCHEN
select * from BENHNHAN
EXEC TIM_NHASI_RANH 1, '2023-12-02 15:00'
GO
--Xóa cuộc hẹn
CREATE OR ALTER PROCEDURE XOA_CUOCHEN
	@ID_CUOCHEN INT
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM CUOCHEN WHERE ID_CUOCHEN = @ID_CUOCHEN)
	BEGIN
		RAISERROR(N'KHÔNG TỒN TẠI ID CUỘC HẸN', 16, 1)
		RETURN
	END;

	DELETE FROM CUOCHEN WHERE ID_CUOCHEN = @ID_CUOCHEN

	IF @@ERROR <> 0
	BEGIN
		RAISERROR('LỖI HỆ THỐNG KO THỂ XÓA CUỘC HẸN', 16, 1)
	END;
END;

EXEC XOA_CUOCHEN 1
GO

-- LỌC CUỘC HẸN RIÊNG CỦA NHA SĨ
CREATE OR ALTER PROCEDURE LOC_CUOCHEN_NHASI
	@ID_NHASI INT
AS
BEGIN
	SELECT * 
	FROM CUOCHEN 
	WHERE ID_NHASI = @ID_NHASI
END;