USE QLPHONGKHAM_CSDLNC;
GO

-- THEO NGÀY 
DECLARE @DATE DATE = '1957-07-02'; 
SELECT NGAYTHANHTOAN, SUM(TONGTIENTHANHTOAN), COUNT(*) 
FROM THONGTIN_THANHTOAN
WHERE TIENDATRA > 0
GROUP BY NGAYTHANHTOAN
HAVING NGAYTHANHTOAN = @DATE
ORDER BY COUNT(*) DESC

-- theo tháng
DECLARE @TODAY DATE = '2000-08-20'; 
DECLARE @FIRST_DAY_OF_MONTH DATE = DATEFROMPARTS(YEAR(@TODAY), MONTH(@TODAY), 1);
DECLARE @LAST_DAY_OF_MONTH DATE = EOMONTH(@TODAY);
--SELECT @FIRST_DAY_OF_MONTH
--SELECT @LAST_DAY_OF_MONTH AS LastDayOfMonth;

-- DOANH THU
SELECT MONTH(NGAYTHANHTOAN), SUM(TIENDATRA) AS DOANHTHU
FROM 
THONGTIN_THANHTOAN
WHERE NGAYTHANHTOAN >= @FIRST_DAY_OF_MONTH
AND NGAYTHANHTOAN <= @LAST_DAY_OF_MONTH
GROUP BY MONTH(NGAYTHANHTOAN)

-- TỔNG NỢ
SELECT MONTH(NGAYTHANHTOAN), SUM(TONGTIENTHANHTOAN) AS DOANHTHU
FROM 
THONGTIN_THANHTOAN
WHERE NGAYTHANHTOAN >= @FIRST_DAY_OF_MONTH
AND NGAYTHANHTOAN <= @LAST_DAY_OF_MONTH AND TIENDATRA = 0
GROUP BY MONTH(NGAYTHANHTOAN)

CREATE OR ALTER FUNCTION DOANHTHU(@BEGINDATE DATE, @ENDDATE DATE)
RETURNS INT
AS
BEGIN
	DECLARE @DOANHTHUDT INT
	SET @DOANHTHUDT = (
		SELECT ISNULL(SUM(TTTDT.TONGTIENTHANHTOAN), 0)
		FROM DONTHUOC DT JOIN THONGTIN_THANHTOAN_DONTHUOC TTTDT  
			 ON DT.ID_DONTHUOC = TTTDT.ID_DONTHUOC
		WHERE TTTDT.NGAYTAODONTHUOC >= @BEGINDATE AND 
			  TTTDT.NGAYTAODONTHUOC <= @ENDDATE
	)

	DECLARE @DOANHTHUDTR INT
	SET @DOANHTHUDTR = (
		SELECT ISNULL(SUM(TTT.TONGTIENTHANHTOAN), 0)
		FROM KEHOACH_DIEUTRI KHDT JOIN THONGTIN_THANHTOAN TTT 
			 ON KHDT.ID_KEHOACH_DIEUTRI = TTT.ID_KEHOACH_DIEUTRI
		WHERE TTT.NGAYTAO_CAC_CHITIET_DIEUTRI >= @BEGINDATE AND 
			  TTT.NGAYTAO_CAC_CHITIET_DIEUTRI <= @ENDDATE
	)
	RETURN @DOANHTHUDTR + @DOANHTHUDT
END
GO

PRINT(dbo.DOANHTHU('2000-1-1', '2000-1-1'))	
GO

CREATE OR ALTER FUNCTION TONGNO(@BEGINDATE DATE, @ENDDATE DATE)
RETURNS INT
AS 
BEGIN
	DECLARE @TONGNODT INT
	SET @TONGNODT = (
		SELECT ISNULL(SUM(TTTDT.TONGTIENTHANHTOAN), 0)
		FROM DONTHUOC DT JOIN THONGTIN_THANHTOAN_DONTHUOC TTTDT ON DT.ID_DONTHUOC = TTTDT.ID_DONTHUOC
		WHERE TTTDT.NGAYTAODONTHUOC >= @BEGINDATE AND 
			  TTTDT.NGAYTAODONTHUOC <= @ENDDATE AND 
			  TTTDT.NGAYTHANHTOAN > @ENDDATE AND TTTDT.TIENDATRA = 0
	)
	DECLARE @TONGNODTR INT
	SET @TONGNODTR = (
		SELECT ISNULL(SUM(TTT.TONGTIENTHANHTOAN), 0)
		FROM KEHOACH_DIEUTRI KHDT JOIN THONGTIN_THANHTOAN TTT  ON KHDT.ID_KEHOACH_DIEUTRI = TTT.ID_KEHOACH_DIEUTRI
		WHERE  TTT.NGAYTAO_CAC_CHITIET_DIEUTRI >= @BEGINDATE AND TTT.NGAYTAO_CAC_CHITIET_DIEUTRI <= @ENDDATE  
		AND TTT.NGAYTHANHTOAN > @ENDDATE AND TTT.TIENDATRA = 0
	)
	RETURN @TONGNODT + @TONGNODTR
END

-- EXPECTED DOANH THU
-- ACTUAL DOANH THU => NỢ = EXPECTED DOANH THU - ACTUAL DOANHTHU
SELECT SUM(TONGTIENTHANHTOAN)
FROM THONGTIN_THANHTOAN_DONTHUOC

select * 
from THONGTIN_THANHTOAN_DONTHUOC
