USE QLPHONGKHAM_CSDLNC;
GO

-- THEO NGÀY 
DECLARE @DATE DATE = '1957-07-02'; 
SELECT NGAYTHANHTOAN, SUM(TONGTIENTHANHTOAN), COUNT(*) 
FROM THONGTIN_THANHTOAN
WHERE TIENDATRA > 0
GROUP BY NGAYTHANHTOAN
HAVING NGAYTHANHTOAN = @DATE
ORDER BY COUNT(*) DESC