USE QLPHONGKHAM_CSDLNC;
GO

-- THEO NGÀY 
DECLARE @DATE DATE = '1957-07-02'; 
SELECT NGAYTHANHTOAN, SUM(TONGTIENTHANHTOAN), COUNT(*) 
FROM THONGTIN_THANHTOAN
WHERE TIENDATRA > 0
GROUP BY NGAYTHANHTOAN
HAVING NGAYTHANHTOAN = @DATE
ORDER BY COUNT(*) DESC

-- theo tháng
DECLARE @TODAY DATE = '2000-08-20'; 
DECLARE @FIRST_DAY_OF_MONTH DATE = DATEFROMPARTS(YEAR(@TODAY), MONTH(@TODAY), 1);
DECLARE @LAST_DAY_OF_MONTH DATE = EOMONTH(@TODAY);
--SELECT @FIRST_DAY_OF_MONTH
--SELECT @LAST_DAY_OF_MONTH AS LastDayOfMonth;

-- DOANH THU
SELECT MONTH(NGAYTHANHTOAN), SUM(TIENDATRA) AS DOANHTHU
FROM 
THONGTIN_THANHTOAN
WHERE NGAYTHANHTOAN >= @FIRST_DAY_OF_MONTH
AND NGAYTHANHTOAN <= @LAST_DAY_OF_MONTH
GROUP BY MONTH(NGAYTHANHTOAN)

-- TỔNG NỢ
SELECT MONTH(NGAYTHANHTOAN), SUM(TONGTIENTHANHTOAN) AS DOANHTHU
FROM 
THONGTIN_THANHTOAN
WHERE NGAYTHANHTOAN >= @FIRST_DAY_OF_MONTH
AND NGAYTHANHTOAN <= @LAST_DAY_OF_MONTH AND TIENDATRA = 0
GROUP BY MONTH(NGAYTHANHTOAN)

go
CREATE OR ALTER FUNCTION DOANHTHU(@BEGINDATE DATE, @ENDDATE DATE)
RETURNS INT
AS
BEGIN
	DECLARE @DOANHTHUDT INT
	SET @DOANHTHUDT = (
		SELECT ISNULL(SUM(TTTDT.TONGTIENTHANHTOAN), 0)
		FROM DONTHUOC DT JOIN THONGTIN_THANHTOAN_DONTHUOC TTTDT  
			 ON DT.ID_DONTHUOC = TTTDT.ID_DONTHUOC
		WHERE TTTDT.NGAYTAODONTHUOC >= @BEGINDATE AND 
			  TTTDT.NGAYTAODONTHUOC <= @ENDDATE
	)

	DECLARE @DOANHTHUDTR INT
	SET @DOANHTHUDTR = (
		SELECT ISNULL(SUM(TTT.TONGTIENTHANHTOAN), 0)
		FROM KEHOACH_DIEUTRI KHDT JOIN THONGTIN_THANHTOAN TTT 
			 ON KHDT.ID_KEHOACH_DIEUTRI = TTT.ID_KEHOACH_DIEUTRI
		WHERE TTT.NGAYTAO_CAC_CHITIET_DIEUTRI >= @BEGINDATE AND 
			  TTT.NGAYTAO_CAC_CHITIET_DIEUTRI <= @ENDDATE
	)
	RETURN @DOANHTHUDTR + @DOANHTHUDT
END
GO

--PRINT(dbo.DOANHTHU('2000-1-1', '2000-1-1'))	
--GO

CREATE OR ALTER FUNCTION TONGNO(@BEGINDATE DATE, @ENDDATE DATE)
RETURNS INT
AS 
BEGIN
	DECLARE @TONGNODT INT
	SET @TONGNODT = (
		SELECT ISNULL(SUM(TTTDT.TONGTIENTHANHTOAN), 0)
		FROM DONTHUOC DT JOIN THONGTIN_THANHTOAN_DONTHUOC TTTDT ON DT.ID_DONTHUOC = TTTDT.ID_DONTHUOC
		WHERE TTTDT.NGAYTAODONTHUOC >= @BEGINDATE AND 
			  TTTDT.NGAYTAODONTHUOC <= @ENDDATE AND 
			  TTTDT.NGAYTHANHTOAN > @ENDDATE AND TTTDT.TIENDATRA = 0
	)
	DECLARE @TONGNODTR INT
	SET @TONGNODTR = (
		SELECT ISNULL(SUM(TTT.TONGTIENTHANHTOAN), 0)
		FROM KEHOACH_DIEUTRI KHDT JOIN THONGTIN_THANHTOAN TTT  ON KHDT.ID_KEHOACH_DIEUTRI = TTT.ID_KEHOACH_DIEUTRI
		WHERE  TTT.NGAYTAO_CAC_CHITIET_DIEUTRI >= @BEGINDATE AND TTT.NGAYTAO_CAC_CHITIET_DIEUTRI <= @ENDDATE  
		AND TTT.NGAYTHANHTOAN > @ENDDATE AND TTT.TIENDATRA = 0
	)
	RETURN @TONGNODT + @TONGNODTR
END
GO

--PRINT(dbo.TONGNO('2000-1-1', '2000-1-1'))
--GO

CREATE OR ALTER PROCEDURE DOANHTHU_THANG 
	@THANGNAM VARCHAR(8) 
AS
BEGIN
	CREATE TABLE #TOTALREVENUE(NGAY DATE, TONGNO INT, TONGDOANHTHU INT)
	DECLARE @BEGINDATE DATE
	DECLARE @ENDDATE DATE
	SET @BEGINDATE = CONVERT(DATE, @THANGNAM + '-01')
	SET @ENDDATE = DATEADD(DAY, -1, DATEADD(MONTH, 1, @BEGINDATE))
	DECLARE @CURRDATE DATE = @BEGINDATE
	WHILE @CURRDATE <= @ENDDATE
	BEGIN
		INSERT INTO #TOTALREVENUE(NGAY,TONGNO, TONGDOANHTHU)
		VALUES
		(   @CURRDATE,
		    dbo.TONGNO(@CURRDATE, @CURRDATE),
		    dbo.DOANHTHU(@CURRDATE, @CURRDATE)
		)
		SET @CURRDATE = DATEADD(DAY, 1, @CURRDATE)
	END
	SELECT * FROM #TOTALREVENUE
	DROP TABLE #TOTALREVENUE
END
GO
SET STATISTICS TIME ON
EXEC dbo.DOANHTHU_THANG @THANGNAM = '2000-02' -- nvarchar(8)
SET STATISTICS TIME OFF
GO

CREATE OR ALTER PROCEDURE DOANHTHU_NAM 
	@NAM VARCHAR(4)
AS
BEGIN
	CREATE TABLE #TOTALREVENUE (THANG VARCHAR(8), TONGNO INT, TONGDOANHTHU INT)
	DECLARE @BEGINDATE DATE
	DECLARE @ENDDATE DATE
	SET @BEGINDATE = CONVERT(DATE, @NAM + '-01-01')
	SET @ENDDATE = DATEADD(DAY, -1, DATEADD(YEAR, 1, @BEGINDATE))
	DECLARE @TEMPDATE DATE = @BEGINDATE
	DECLARE @CURRMONTH VARCHAR(8)
	WHILE(@TEMPDATE <= @ENDDATE)
	BEGIN
		SET @CURRMONTH = FORMAT(@TEMPDATE, 'yyyy-MM')	
		INSERT INTO #TOTALREVENUE(THANG, TONGNO, TONGDOANHTHU)
		VALUES
		(   @CURRMONTH, -- THANG - varchar(8)
		    dbo.TONGNO(@TEMPDATE, DATEADD(DAY, -1, DATEADD(MONTH, 1, @TEMPDATE))), -- TONGNO - int
		    dbo.DOANHTHU(@TEMPDATE, DATEADD(DAY, -1, DATEADD(MONTH, 1, @TEMPDATE)))  -- TONGDOANHTHU - int
		)
		SET @TEMPDATE = DATEADD(MONTH, 1 , @TEMPDATE)
	END
	SELECT * FROM #TOTALREVENUE
	DROP TABLE #TOTALREVENUE
END
GO

SET STATISTICS TIME ON
EXEC dbo.DOANHTHU_NAM @NAM = '2001' -- varchar(4)
SET STATISTICS TIME OFF
GO
