USE QLPHONGKHAM_CSDLNC; 
GO 

-- THÊM KẾ HOẠCH ĐIỀU TRỊ
CREATE OR ALTER PROCEDURE THEM_KEHOACH_DIEUTRI
    @NOIDUNG NVARCHAR(100),
    @CHANDOAN NVARCHAR(100),
    @ID_BENHNHAN INT,
    @OUTPUT_ID INT OUTPUT
AS
BEGIN
    IF NOT EXISTS(SELECT 1 FROM BENHNHAN WHERE ID_BENHNHAN = @ID_BENHNHAN)
    BEGIN
        RAISERROR(N'KO TỒN TẠI BỆNH NHÂN', 16, 1)
        RETURN
    END;

    INSERT INTO KEHOACH_DIEUTRI(ID_BENHNHAN, NOIDUNG, CHANDOAN)
    VALUES (@ID_BENHNHAN, @NOIDUNG, @CHANDOAN)
	
	-- TRẢ VỀ ID_KEHOACH_DIEUTRI VỪA INSERT
    SELECT TOP 1 @OUTPUT_ID = ID_KEHOACH_DIEUTRI 
    FROM KEHOACH_DIEUTRI 
    ORDER BY ID_KEHOACH_DIEUTRI DESC
END;
GO

DECLARE @OUTPUT_ID INT
EXEC THEM_KEHOACH_DIEUTRI N'NHỔ RĂNG', N'SÂU RĂNG', 1, @OUTPUT_ID = @OUTPUT_ID OUTPUT
SELECT @OUTPUT_ID AS ID_KEHOACH_DIEUTRIEXEC 
GO

-- CẬP NHẬT KẾ HOẠCH ĐIỀU TRỊ
CREATE OR ALTER PROCEDURE CAPNHAT_KEHOACH_DIEUTRI
	@ID_KEHOACH_DIEUTRI INT,
	@NOIDUNG NVARCHAR(100),
	@CHANDOAN NVARCHAR(100),
	@TINHTRANGDIEUTRI TINYINT
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM KEHOACH_DIEUTRI WHERE ID_KEHOACH_DIEUTRI = @ID_KEHOACH_DIEUTRI)
	BEGIN
		RAISERROR(N'KO TỒN TẠI KẾ HOẠCH NÀY', 16, 1)
		RETURN;
	END; 
	UPDATE KEHOACH_DIEUTRI
	SET NOIDUNG = @NOIDUNG,
		CHANDOAN = @CHANDOAN,
		TINHTRANGDIEUTRI = @TINHTRANGDIEUTRI
	WHERE ID_KEHOACH_DIEUTRI = @ID_KEHOACH_DIEUTRI

	IF @@ERROR <> 0
	BEGIN
		RAISERROR(N'LỖI HỆ THỐNG', 16, 1)
		RETURN
	END;
END; 
go

EXEC CAPNHAT_KEHOACH_DIEUTRI 1, N'UPDATE', N'UPDATE', 1
GO
-- THÊM CHI TIẾT ĐIỀU TRỊ 
CREATE OR ALTER PROCEDURE THEM_CHITIET_DIEUTRI
	@ID_DIEUTRI INT,
	@ID_KEHOACH_DIEUTRI INT,
	@ID_RANG TINYINT,
	@LOAIMAT CHAR(1)
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM DIEUTRI WHERE ID_DIEUTRI = @ID_DIEUTRI)
	BEGIN
		RAISERROR(N'ĐIỀU TRỊ KO TỒN TẠI', 16, 1)
		RETURN
	END;

	IF NOT EXISTS(SELECT 1 FROM KEHOACH_DIEUTRI WHERE ID_KEHOACH_DIEUTRI = @ID_KEHOACH_DIEUTRI)
	BEGIN
		RAISERROR(N'KẾ HOẠCH ĐIỀU TRỊ KO TỒN TẠI', 16, 1)
		RETURN
	END; 

	IF NOT EXISTS(SELECT 1 FROM RANG WHERE ID_RANG = @ID_RANG)
	BEGIN
		RAISERROR(N'RĂNG KO TỒN TẠI', 16, 1)
		RETURN
	END;

	
	IF NOT EXISTS(SELECT 1 FROM MAT WHERE LOAIMAT = @LOAIMAT)
	BEGIN
		RAISERROR(N'MẶT KO TỒN TẠI', 16, 1)
		RETURN
	END;

	INSERT INTO CHITIET_DIEUTRI(ID_KEHOACH_DIEUTRI, ID_DIEUTRI,ID_RANG, LOAIMAT)
	VALUES (@ID_KEHOACH_DIEUTRI, @ID_DIEUTRI, @ID_RANG, @LOAIMAT)

	-- CẬP NHẬT TỔNG CHI PHÍ CỦA KẾ HOẠCH ĐIỀU TRỊ
	UPDATE KEHOACH_DIEUTRI
	SET TONG_CHIPHI = TONG_CHIPHI + (SELECT PHI FROM DIEUTRI WHERE ID_DIEUTRI = @ID_DIEUTRI)
	WHERE ID_KEHOACH_DIEUTRI = @ID_KEHOACH_DIEUTRI

END; 
GO

EXEC THEM_CHITIET_DIEUTRI 1, 4, 2, 'L'

-- XEM KẾ HOẠCH ĐIỀU TRỊ CỤ THỂ
CREATE OR ALTER PROCEDURE XEM_KEHOACH_DIEUTRI_CUTHE
	@ID_KEHOACH_DIEUTRI INT
AS
BEGIN
	SELECT R.TEN_RANG, M.TENMAT, DT.TENDIEUTRI, DT.PHI
	FROM CHITIET_DIEUTRI CTDT
	JOIN RANG R ON R.ID_RANG = CTDT.ID_RANG
	JOIN MAT M ON M.LOAIMAT = CTDT.LOAIMAT
	JOIN DIEUTRI DT ON DT.ID_DIEUTRI = CTDT.ID_DIEUTRI
END; 
GO

EXEC XEM_KEHOACH_DIEUTRI_CUTHE 4