USE QLPHONGKHAM_CSDLNC;
GO

CREATE OR ALTER PROCEDURE TAO_LICH_LAM_VIEC
	@ID_LICHLAMVIEC NCHAR(10),
	@ID_NHANVIEN NCHAR(10),
	@ID_PHONGKHAM NCHAR(10),
	@GIO_BATDAU DATETIME,
	@GIO_KETTHUC DATETIME
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM NHANVIEN WHERE ID_NHANVIEN = @ID_NHANVIEN)
	BEGIN
		RAISERROR(N'KO TỒN TẠI NHÂN VIÊN NÀY', 16, 1)
		RETURN
	END;
	
	IF @GIO_BATDAU > @GIO_KETTHUC
	BEGIN
		RAISERROR(N'GIỜ BẮT ĐẦU < GIỜ KẾT THÚC', 16, 1)
		RETURN
	END;

	INSERT INTO LICHLAMVIEC(ID_LICHLAMVIEC, ID_NV_LLV, GIOBATDAU, GIOKETTHUC, PHONGKHAM)
	VALUES(@ID_LICHLAMVIEC, @ID_NHANVIEN, @GIO_BATDAU, @GIO_KETTHUC, @ID_PHONGKHAM)
END;
GO

INSERT INTO PHONGKHAM(ID_PHONGKHAM, DIACHIPK, SDTPK)
VALUES ('PK001', 'Q8', '123123')

SELECT * 
FROM LICHLAMVIEC LLV 
JOIN NHANVIEN NV ON NV.ID_NHANVIEN = LLV.ID_NV_LLV

SELECT * FROM LICHLAMVIEC WHERE DATEPART(HOUR, GIOBATDAU) = 0


