USE QLPHONGKHAM_CSDLNC;
GO

-- XEM LICH LAM VIEC CUA NHAN VIEN 
CREATE OR ALTER PROCEDURE XEM_LICHLAMVIEC_NHANVIEN
	@ID_NHANVIEN INT
AS
BEGIN
	SELECT GIOBATDAU, GIOKETTHUC
	FROM LICHLAMVIEC 
	WHERE ID_NHANVIEN = @ID_NHANVIEN
	ORDER BY GIOBATDAU
END;
GO

CREATE OR ALTER FUNCTION KIEMTRA_TRUNG_LICHLAMVIEC (@ID_NHANVIEN INT, 
													@GIO_BATDAU DATETIME, @GIO_KETTHUC DATETIME)
RETURNS BIT
AS
BEGIN
	-- CHECK CÓ LẶP GIỜ LÀM VIỆC KHÔNG
	IF EXISTS(
	SELECT 1 FROM LICHLAMVIEC LLV 
	WHERE LLV.ID_NHANVIEN = @ID_NHANVIEN
	AND @GIO_BATDAU >= LLV.GIOBATDAU AND @GIO_KETTHUC <= LLV.GIOKETTHUC)
	BEGIN
		RETURN 1
	END;
	RETURN 0
END;
GO
-- TẠO LỊCH LÀM VIỆC
CREATE OR ALTER PROCEDURE TAO_LICHLAMVIEC
	@ID_NHANVIEN INT,
	@ID_PHONGKHAM INT,
	@GIO_BATDAU DATETIME
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM NHANVIEN WHERE ID_NHANVIEN = @ID_NHANVIEN)
	BEGIN
		RAISERROR(N'KO TỒN TẠI NHÂN VIÊN NÀY', 16, 1)
		RETURN
	END;
	DECLARE @GIO_KETTHUC DATETIME;
	SELECT @GIO_KETTHUC = DATEADD(HOUR, 4, @GIO_BATDAU)
	-- CHECK CÓ LẶP GIỜ LÀM VIỆC KHÔNG
	IF DBO.KIEMTRA_TRUNG_LICHLAMVIEC(@ID_NHANVIEN, @GIO_BATDAU, @GIO_KETTHUC) = 1
	BEGIN
		RAISERROR(N'NHÂN VIÊN ĐÃ CÓ LỊCH LÀM VIỆC VÀO GIỜ NÀY', 16, 1)
		RETURN
	END

	INSERT INTO LICHLAMVIEC(ID_NHANVIEN, GIOBATDAU, GIOKETTHUC, ID_PHONGKHAM)
	VALUES(@ID_NHANVIEN, @GIO_BATDAU, @GIO_KETTHUC, @ID_PHONGKHAM)
END;
GO

SELECT * FROM LICHLAMVIEC
EXEC TAO_LICHLAMVIEC 1, 1, '2023-01-28 6:00'
EXEC TAO_LICHLAMVIEC 1, 1, '2023-01-29 6:00'



INSERT INTO PHONGKHAM(ID_PHONGKHAM, DIACHIPK, SDTPK)
VALUES ('PK001', 'Q8', '123123')
GO

-- tìm kiếm những nha sĩ rảnh vào giờ hẹn và chưa có cuộc hẹn nào vào giờ đó
CREATE OR ALTER PROCEDURE TIM_NHASI_RANH
	@ID_BENHNHAN INT,
    @GIO_BATDAU DATETIME
AS
BEGIN
    DECLARE @DS_NHASI TABLE (
        ID_NHANVIEN INT,
		TEN NVARCHAR(50)
    );

	DECLARE @GIO_KETTHUC DATETIME;
	SELECT @GIO_KETTHUC = DATEADD(HOUR, 1, @GIO_BATDAU)

    INSERT INTO @DS_NHASI (ID_NHANVIEN, TEN)
    SELECT NV.ID_NHANVIEN, NV.TEN
    FROM NHANVIEN NV
    JOIN LICHLAMVIEC LLV ON LLV.ID_NHANVIEN = NV.ID_NHANVIEN
	WHERE NV.LOAINHANVIEN = N'Nha sĩ'
	AND LLV.GIOBATDAU <= @GIO_BATDAU AND LLV.GIOKETTHUC >= @GIO_BATDAU
	AND NV.ID_NHANVIEN NOT IN (
        SELECT CH.ID_NHASI
        FROM CUOCHEN CH
        WHERE CH.THOIGIAN >= @GIO_BATDAU AND DATEADD(HOUR, 1, CH.THOIGIAN) <= @GIO_KETTHUC
    );

    SELECT DS.ID_NHANVIEN, DS.TEN, 1 AS DA_KHAM
    FROM @DS_NHASI DS WHERE DS.ID_NHANVIEN IN 
	(SELECT CH.ID_NHASI FROM CUOCHEN CH WHERE CH.ID_BENHNHAN = @ID_BENHNHAN)
	UNION ALL
	SELECT DS.ID_NHANVIEN, DS.TEN, 0 AS DA_KHAM
	FROM @DS_NHASI DS WHERE DS.ID_NHANVIEN NOT IN
	(SELECT CH.ID_NHASI FROM CUOCHEN CH WHERE CH.ID_BENHNHAN = @ID_BENHNHAN)
END;
GO
 
EXEC TIM_NHASI_RANH 1, '2023-10-27 06:00'
GO

-- XEM LỊCH LÀM VIỆC CỦA MỖI NV
CREATE OR ALTER PROCEDURE XEM_LICHLAMVIEC_NHANVIEN
	@ID_NHANVIEN INT
AS
BEGIN
	SELECT TOP 10 LLV.GIOBATDAU, LLV.GIOKETTHUC, PK.DIACHIPK 
	FROM LICHLAMVIEC LLV
	JOIN PHONGKHAM PK ON PK.ID_PHONGKHAM = LLV.ID_PHONGKHAM
	WHERE ID_NHANVIEN = @ID_NHANVIEN
END
GO

EXEC XEM_LICHLAMVIEC_NHANVIEN 1
select * from NHANVIEN


