USE QLPHONGKHAM_CSDLNC
GO
--Lọc cuộc hẹn theo BN, PK, NS
CREATE OR ALTER PROCEDURE XEM_CUOCHEN_BN
	@ID_BENHNHAN NCHAR(10)
AS
BEGIN
	SELECT *
	FROM CUOCHEN ch
	WHERE ch.ID_BENHNHAN = @ID_BENHNHAN
END;
GO

CREATE OR ALTER PROCEDURE XEM_CUOCHEN_PK
	@ID_PHONGKHAM NCHAR(10)
AS
BEGIN
	SELECT *
	FROM CUOCHEN ch
	WHERE ch.ID_PHONGKHAM = @ID_PHONGKHAM
END;
GO

CREATE OR ALTER PROCEDURE XEM_CUOCHEN_NS
	@ID_NHASI NCHAR(10)
AS
BEGIN
	SELECT *
	FROM CUOCHEN ch
	WHERE ch.ID_NHASI = @ID_NHASI
END;
GO

--Xem danh sách nha sĩ
CREATE OR ALTER PROCEDURE XEM_DSNHASI
AS
BEGIN
	SELECT nv.*
	FROM NHANVIEN nv
	join NHASI ns on nv.ID_NHANVIEN = ns.ID_NHASI
END;
GO

--Xem danh sách nhân viên
CREATE OR ALTER PROCEDURE XEM_DSNHANVIEN
AS
BEGIN
	SELECT *
	FROM NHANVIEN 
END;
GO
--Xem danh sách nha sĩ và lịch trình làm việc tương ứng
CREATE OR ALTER PROCEDURE XEM_LICHTRINHNHASI
AS
BEGIN
	SELECT nv.ID_NHANVIEN, nv.TEN, llv.NGAYTHANGNAM, llv.GIOBATDAU, llv.GIOKETTHUC, llv.PHONGKHAM
	FROM NHANVIEN nv, NHASI ns, LICHLAMVIEC llv
	where nv.ID_NHANVIEN = llv.ID_NV_LLV and nv.ID_NHANVIEN = ns.ID_NHASI
END;
GO

exec XEM_LICHTRINHNHASI
go
--Thêm / Cập nhật thông tin nha sĩ.
CREATE OR ALTER PROCEDURE THEM_NHASI
	@ID_NHANVIEN NCHAR(10),
	@TEN NVARCHAR(50),
	@NGAYSINH DATE,
	@DIACHI NVARCHAR(50),
	@EMAIL NVARCHAR(20),
	@SODIENTHOAI NCHAR(10)
AS
BEGIN
	IF EXISTS(SELECT 1 FROM NHANVIEN WHERE ID_NHANVIEN = @ID_NHANVIEN)
	BEGIN
		RAISERROR(N'ĐÃ CÓ ID NHÂN VIÊN', 16, 1)
		RETURN
	END;
	IF EXISTS(SELECT 1 FROM NHANVIEN WHERE EMAIL = @EMAIL)
	BEGIN
		RAISERROR(N'ĐÃ CÓ EMAIL NHÂN VIÊN', 16, 1)
		RETURN
	END;
	IF EXISTS(SELECT 1 FROM NHANVIEN WHERE SODIENTHOAI = @SODIENTHOAI)
	BEGIN
		RAISERROR(N'ĐÃ CÓ SĐT NHÂN VIÊN', 16, 1)
		RETURN
	END;
	INSERT INTO NHANVIEN(ID_NHANVIEN, TEN, NGAYSINH, DIACHI, EMAIL, SODIENTHOAI)
	values 
		(@ID_NHANVIEN, @TEN, @NGAYSINH, @DIACHI, @EMAIL, @SODIENTHOAI)
	INSERT INTO NHASI(ID_NHASI) values (@ID_NHANVIEN)
	IF @@ERROR <> 0
	BEGIN
		RAISERROR('LỖI HỆ THỐNG KO THỂ THÊM BỆNH NHÂN', 16, 1)
	END;
END;
GO

--update NHASI
CREATE OR ALTER PROCEDURE UPD_NHASI
	@ID_NHANVIEN NCHAR(10),
	@TEN NVARCHAR(50),
	@NGAYSINH DATE,
	@DIACHI NVARCHAR(50),
	@EMAIL NVARCHAR(20),
	@SODIENTHOAI NCHAR(10)
AS
BEGIN
	UPDATE NHANVIEN
	SET 
		TEN = @TEN,
		NGAYSINH = @NGAYSINH,
		DIACHI = @DIACHI,
		EMAIL = @EMAIL,
		SODIENTHOAI = @SODIENTHOAI
	WHERE ID_NHANVIEN = @ID_NHANVIEN
END;
GO

--Thêm / Cập nhật thông tin nhân viên
CREATE OR ALTER PROCEDURE THEM_NHANVIEN
	@ID_NHANVIEN NCHAR(10),
	@TEN NVARCHAR(50),
	@NGAYSINH DATE,
	@DIACHI NVARCHAR(50),
	@EMAIL NVARCHAR(20),
	@SODIENTHOAI NCHAR(10)
AS
BEGIN
	IF EXISTS(SELECT 1 FROM NHANVIEN WHERE ID_NHANVIEN = @ID_NHANVIEN)
	BEGIN
		RAISERROR(N'ĐÃ CÓ ID NHÂN VIÊN', 16, 1)
		RETURN
	END;
	IF EXISTS(SELECT 1 FROM NHANVIEN WHERE EMAIL = @EMAIL)
	BEGIN
		RAISERROR(N'ĐÃ CÓ EMAIL NHÂN VIÊN', 16, 1)
		RETURN
	END;
	IF EXISTS(SELECT 1 FROM NHANVIEN WHERE SODIENTHOAI = @SODIENTHOAI)
	BEGIN
		RAISERROR(N'ĐÃ CÓ SĐT NHÂN VIÊN', 16, 1)
		RETURN
	END;
	INSERT INTO NHANVIEN(ID_NHANVIEN, TEN, NGAYSINH, DIACHI, EMAIL, SODIENTHOAI)
	values 
		(@ID_NHANVIEN, @TEN, @NGAYSINH, @DIACHI, @EMAIL, @SODIENTHOAI)
	IF @@ERROR <> 0
	BEGIN
		RAISERROR('LỖI HỆ THỐNG KO THỂ THÊM BỆNH NHÂN', 16, 1)
	END;
END;
GO

--update NHANVIEN
CREATE OR ALTER PROCEDURE UPD_NHANVIEN
	@ID_NHANVIEN NCHAR(10),
	@TEN NVARCHAR(50),
	@NGAYSINH DATE,
	@DIACHI NVARCHAR(50),
	@EMAIL NVARCHAR(20),
	@SODIENTHOAI NCHAR(10)
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM NHANVIEN WHERE ID_NHANVIEN = @ID_NHANVIEN)
	BEGIN
		RAISERROR(N'KHÔNG TỒN TẠI ID NHÂN VIÊN', 16, 1)
		RETURN
	END;
	UPDATE NHANVIEN
	SET 
		TEN = @TEN,
		NGAYSINH = @NGAYSINH,
		DIACHI = @DIACHI,
		EMAIL = @EMAIL,
		SODIENTHOAI = @SODIENTHOAI
	WHERE ID_NHANVIEN = @ID_NHANVIEN
	IF @@ERROR <> 0
	BEGIN
		RAISERROR('LỖI HỆ THỐNG KO THỂ CẬP NHẬT BỆNH NHÂN', 16, 1)
	END;
END;
GO
--Thêm lịch làm việc cho nha sĩ.
CREATE OR ALTER PROCEDURE THEM_LLV 
	@ID_LICHLAMVIEC NCHAR(10),
	@ID_NV_LLV NCHAR(10),
	@NGAYTHANGNAM DATE,
	@GIOBATDAU DATETIME,
	@GIOKETTHUC DATETIME,
	@PHONGKHAM NCHAR(10)
AS
BEGIN
	IF EXISTS(SELECT 1 FROM LICHLAMVIEC WHERE ID_LICHLAMVIEC = @ID_LICHLAMVIEC)
	BEGIN
		RAISERROR(N'ĐÃ CÓ ID LLV', 16, 1)
		RETURN
	END;
	IF NOT EXISTS(SELECT 1 FROM NHASI WHERE ID_NHASI = @ID_NV_LLV)
	BEGIN
		RAISERROR(N'NHÂN VIÊN KHÔNG PHẢI NHA SĨ', 16, 1)
		RETURN
	END;
	INSERT INTO LICHLAMVIEC
		(ID_LICHLAMVIEC, ID_NV_LLV, NGAYTHANGNAM, GIOBATDAU, GIOKETTHUC, PHONGKHAM)
	VALUES
		(@ID_LICHLAMVIEC, @ID_NV_LLV, @NGAYTHANGNAM, @GIOBATDAU, @GIOKETTHUC, @PHONGKHAM)
	IF @@ERROR <> 0
	BEGIN
		RAISERROR('LỖI HỆ THỐNG KO THỂ THÊM LỊCH LÀM VIỆC', 16, 1)
	END;
END;
GO

--Xem danh sách thuốc: quản trị viên, nhân viên, nha sĩ.
CREATE OR ALTER PROCEDURE XEM_DSTHUOC
AS
BEGIN
	SELECT *
	FROM THUOC
END;
GO
--Thêm / Cập nhật / Xóa thuốc: quản trị viên.
CREATE OR ALTER PROCEDURE THEM_THUOC
	@ID_THUOC NCHAR(10),
	@TEN_THUOC NVARCHAR(20),
	@PHI DECIMAL(18,2),
	@DONVITINH NVARCHAR(5)
AS
BEGIN
	IF EXISTS(SELECT 1 FROM THUOC WHERE ID_THUOC = @ID_THUOC)
	BEGIN
		RAISERROR(N'ĐÃ CÓ ID THUOC', 16, 1)
		RETURN
	END;
	INSERT INTO THUOC 
		(ID_THUOC, TEN_THUOC, PHI, DONVITINH)
	VALUES
		(@ID_THUOC, @TEN_THUOC, @PHI, @DONVITINH)
	IF @@ERROR <> 0
	BEGIN
		RAISERROR('LỖI HỆ THỐNG KO THỂ THÊM THUỐC', 16, 1)
	END;
END;
GO

--UPD THUOC
CREATE OR ALTER PROCEDURE UPD_THUOC
	@ID_THUOC NCHAR(10),
	@TEN_THUOC NVARCHAR(20),
	@PHI DECIMAL(18,2),
	@DONVITINH NVARCHAR(5)
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM THUOC WHERE ID_THUOC = @ID_THUOC)
	BEGIN
		RAISERROR(N'KHÔNG TỒN TẠI ID THUỐC', 16, 1)
		RETURN
	END;
	UPDATE THUOC
	SET 
		TEN_THUOC = @TEN_THUOC,
		PHI = @PHI,
		DONVITINH = @DONVITINH
	WHERE ID_THUOC = @ID_THUOC
	IF @@ERROR <> 0
	BEGIN
		RAISERROR('LỖI HỆ THỐNG KO THỂ CẬP NHẬT THUỐC', 16, 1)
	END;
END;
GO

--XOA THUOC
CREATE OR ALTER PROCEDURE XOA_THUOC
	@ID_THUOC NCHAR(10)
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM THUOC WHERE ID_THUOC = @ID_THUOC)
	BEGIN
		RAISERROR(N'KHÔNG TỒN TẠI ID THUỐC', 16, 1)
		RETURN
	END;
	DELETE FROM THUOC WHERE ID_THUOC = @ID_THUOC
	IF @@ERROR <> 0
	BEGIN
		RAISERROR('LỖI HỆ THỐNG KO THỂ XÓA THUỐC', 16, 1)
	END;
END;
GO
--Số lượng thuốc được cập nhật khi có đơn thuốc mới
CREATE TRIGGER TRG_DONTHUOCSLT ON CHITIETDONTHUOC AFTER INSERT AS
BEGIN
	UPDATE QUANLYTHUOC
	SET SOLUONGTON = SOLUONGTON - (
		SELECT i.SOLUONG
		FROM inserted i, BUOIDIEUTRI bdt, DONTHUOC dt
		WHERE i.ID_DT_CT = dt.ID_DONTHUOC and bdt.ID_DONTHUOC = dt.ID_DONTHUOC
			and bdt.ID_PHONGKHAM = QUANLYTHUOC.ID_PHONGKHAM)
END
GO

--update chitietdonthuoc update slt
CREATE TRIGGER TRG_CAPNHATCTDT ON CHITIETDONTHUOC AFTER UPDATE AS
BEGIN
	UPDATE QUANLYTHUOC 
	SET SOLUONGTON = SOLUONGTON - 
		(SELECT SOLUONG FROM inserted i, BUOIDIEUTRI bdt, DONTHUOC dt WHERE i.ID_DT_CT = dt.ID_DONTHUOC and bdt.ID_DONTHUOC = dt.ID_DONTHUOC
			and bdt.ID_PHONGKHAM = QUANLYTHUOC.ID_PHONGKHAM) + 
		(SELECT SOLUONG FROM deleted d, BUOIDIEUTRI bdt, DONTHUOC dt WHERE d.ID_DT_CT = dt.ID_DONTHUOC and bdt.ID_DONTHUOC = dt.ID_DONTHUOC
			and bdt.ID_PHONGKHAM = QUANLYTHUOC.ID_PHONGKHAM)
END 
GO