USE QLPHONGKHAM_CSDLNC;
GO


-- Báo cáo các điều trị trong ngày, theo từng bác sĩ.
CREATE OR ALTER PROCEDURE BAOCAO_DIEUTRI
	@NGAY DATE
AS
BEGIN
	SELECT ID_NHASI, 
		SUM(PHI) AS PHI_DIEU_TRI,
		SUM(THANHTOAN.TIENDATRA) AS TONG_TIEN_DA_THANH_TOAN
	FROM BUOIDIEUTRI BDT
	JOIN THONGTINTHANHTOAN THANHTOAN ON THANHTOAN.ID_THANHTOAN = BDT.ID_TT_BDT
	WHERE NGAYDIEUTRI = @NGAY
	GROUP BY ID_NHASI
END;
GO

-- Báo cáo các cuộc hẹn từ ngày đến ngày, theo từng bác sĩ
CREATE OR ALTER PROCEDURE BAOCAO_DIEUTRI
	@NGAY_BATDAU DATE,
	@NGAY_KETTHUC DATE
AS
BEGIN
	SELECT ID_NHASI, 
		COUNT(*) AS SO_CUOC_HEN
	FROM CUOCHEN
	WHERE CONVERT(DATE, THOIGIAN) BETWEEN @NGAY_BATDAU AND @NGAY_KETTHUC 
	GROUP BY ID_NHASI
END;
GO