USE QLPHONGKHAM_CSDLNC;
GO

-- XEM LỊCH LÀM VIỆC CỦA NHÂN VIÊN
CREATE OR ALTER PROCEDURE XEM_LICHLAMVIEC_NHANVIEN
	@ID_NHANVIEN NCHAR(10)
AS
BEGIN
	SELECT GIOBATDAU, GIOKETTHUC
	FROM LICHLAMVIEC 
	WHERE ID_NV_LLV = @ID_NHANVIEN
	ORDER BY GIOBATDAU
END;
GO
EXEC XEM_LICHLAMVIEC_NHANVIEN 'NV001'

-- đăng ký cho bệnh nhân
CREATE OR ALTER PROCEDURE DANG_KY 
	@DIENTHOAI NCHAR(10),
	@MATKHAU NCHAR(20)
AS
BEGIN
	IF EXISTS(SELECT DIENTHOAI FROM TAIKHOAN WHERE DIENTHOAI = @DIENTHOAI)
	BEGIN
		RAISERROR(N'ĐIỆN THOẠI ĐÃ ĐƯỢC SỬ DỤNG', 16, 1)
		RETURN 1
	END; 

	INSERT INTO TAIKHOAN(DIENTHOAI, MATKHAU)
	VALUES (@DIENTHOAI, @MATKHAU)
	
	IF @@ERROR <> 0
	BEGIN
		RAISERROR(N'LỖI HỆ THỐNG KO THỂ TẠO TÀI KHOẢN', 16, 1)
		RETURN -1
	END; 
END;
GO

-- đang nhập cho nhân viên
CREATE OR ALTER PROCEDURE DANG_NHAP_NHANVIEN
	@SODIENTHOAI NCHAR(10),
	@MATKHAU NCHAR(20)
AS
BEGIN
	IF NOT EXISTS(
		SELECT 1 FROM NHANVIEN NV WHERE NV.SODIENTHOAI = @SODIENTHOAI
	)
	BEGIN
		RAISERROR(N'KHÔNG TỒN TẠI NHÂN VIÊN VỚI SỐ ĐIỆN THOẠI NÀY', 16, 1)
		RETURN 
	END;

	DECLARE @MATKHAUTAIKHOAN NCHAR(20);
	SELECT @MATKHAUTAIKHOAN = TK.MATKHAU FROM TAIKHOAN TK WHERE TK.DIENTHOAI = @SODIENTHOAI

	IF @MATKHAUTAIKHOAN != @MATKHAU
	BEGIN
		RAISERROR(N'SAI MẬT KHẨU', 16, 1)
		RETURN
	END; 

	SELECT TEN, SODIENTHOAI, LOAINHANVIEN
	FROM NHANVIEN
END; 
GO

-- tạo nhân viên
CREATE OR ALTER PROCEDURE TAO_NHAN_VIEN
	@ID_NHANVIEN NCHAR(10),
	@TEN NVARCHAR(50),
	@NGAYSINH DATE, 
	@DIACHI NVARCHAR(50),
	@EMAIL NCHAR(20),
	@SODIENTHOAI NCHAR(10),
	@LOAINHANVIEN NVARCHAR(11)
AS
BEGIN
	IF EXISTS(SELECT ID_NHANVIEN FROM NHANVIEN WHERE ID_NHANVIEN = @ID_NHANVIEN)
	BEGIN
		RAISERROR(N'ID NHÂN VIÊN ĐÃ TỒN TẠI', 16, 1)
		RETURN
	END;

	IF EXISTS(SELECT 1 FROM TAIKHOAN WHERE DIENTHOAI = @SODIENTHOAI)
	BEGIN
		RAISERROR(N'SỐ ĐIỆN THOẠI ĐÃ ĐƯỢC DÙNG', 16, 1)
		RETURN
	END;

	-- tạo tài khoản cho nhân viên
	INSERT INTO TAIKHOAN(DIENTHOAI, MATKHAU)
	VALUES (@SODIENTHOAI, @EMAIL)
	
	-- tạo nhân viên
	INSERT INTO NHANVIEN(ID_NHANVIEN, TEN, NGAYSINH, DIACHI, EMAIL, SODIENTHOAI, LOAINHANVIEN)
	VALUES (@ID_NHANVIEN, @TEN, @NGAYSINH, @DIACHI, @EMAIL, @SODIENTHOAI, @LOAINHANVIEN)
	
	IF @@ERROR <> 0
	BEGIN
		RAISERROR(N'LỖI HỆ THỐNG KHÔNG THỂ THÊM NHÂN VIÊN', 16, 1)
		RETURN
	END; 
END;
GO

-- Xem danh sách bệnh nhân
CREATE OR ALTER PROCEDURE XEM_DS_BENH_NHAN
AS
BEGIN
	SELECT * FROM BENHNHAN
END;
GO

-- Tạo cuộc hẹn
CREATE OR ALTER PROCEDURE TAO_CUOC_HEN
AS
BEGIN
	SELECT * FROM BENHNHAN
END;
GO

-- Thêm bệnh nhân
CREATE OR ALTER PROCEDURE THEM_BENHNHAN 
	@ID_BENHNHAN NCHAR(10),
	@TEN NVARCHAR(50),
	@NGAYSINH DATE,
	@GIOITINH NVARCHAR(3),
	@DIACHI NVARCHAR(100),
	@EMAIL NCHAR(20)
AS 
BEGIN
	IF EXISTS(SELECT 1 FROM BENHNHAN WHERE ID_BENHNHAN = @ID_BENHNHAN)
	BEGIN
		RAISERROR('ĐÃ CÓ ID BỆNH NHÂN', 16, 1)
		RETURN
	END;
	
	INSERT INTO BENHNHAN(ID_BENHNHAN, TEN, NGAYSINH, GIOITINH, DIACHI, EMAIL)
	VALUES 
		(@ID_BENHNHAN, @TEN, @NGAYSINH, @GIOITINH, @DIACHI, @EMAIL)
	IF @@ERROR <> 0
	BEGIN
		RAISERROR('LỖI HỆ THỐNG KO THỂ THÊM BỆNH NHÂN', 16, 1)
	END;
END;
GO

-- Cập nhật bệnh nhân
CREATE OR ALTER PROCEDURE THEM_BENHNHAN 
	@ID_BENHNHAN NCHAR(10),
	@TEN NVARCHAR(50),
	@NGAYSINH DATE,
	@GIOITINH NVARCHAR(3),
	@DIACHI NVARCHAR(100),
	@EMAIL NCHAR(20)
AS 
BEGIN
	IF EXISTS(SELECT 1 FROM BENHNHAN WHERE ID_BENHNHAN = @ID_BENHNHAN)
	BEGIN
		RAISERROR('ĐÃ CÓ ID BỆNH NHÂN', 16, 1)
		RETURN
	END;
	
	UPDATE BENHNHAN
	SET 
		TEN = @TEN,
		NGAYSINH = @NGAYSINH,
		GIOITINH = @GIOITINH,
		DIACHI = @DIACHI,
		EMAIL = @EMAIL
	WHERE ID_BENHNHAN = @ID_BENHNHAN
	
	IF @@ERROR <> 0
	BEGIN
		RAISERROR('LỖI HỆ THỐNG KO THỂ CẬP NHẬT BỆNH NHÂN', 16, 1)
	END;
END;
GO

-- Cập nhật thông tin chống chỉ định thuốc của bệnh nhân.
CREATE OR ALTER PROCEDURE CAPNHAT_THUOCCHONGCHIDINH
	@ID_BENHNHAN NCHAR(10),
	@THUOCCHONGCHIDINH NVARCHAR(150)
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM HOSOBENHNHAN WHERE IDBENHNHAN_HSBN = @ID_BENHNHAN)
	BEGIN
		RAISERROR('HỒ SƠ BỆNH NHÂN KHÔNG TỒN TẠI', 16, 1)
		RETURN
	END;

	UPDATE HOSOBENHNHAN
	SET CHONGCHIDINH = @THUOCCHONGCHIDINH

	IF @@ERROR <> 0
	BEGIN
		RAISERROR('LỖI HỆ THỐNG KHI CẬP NHẬT THUỐC CHỐNG CHỈ ĐỊNH', 16, 1)
		RETURN
	END; 
END
GO

-- Xem kế hoạch điều trị cụ thể.
CREATE OR ALTER PROCEDURE XEM_KEHOACHDIEUTRI
	@ID_HOSOBENHNHAN NCHAR(10)
AS
BEGIN
	SELECT BDT.*
	FROM KEHOACHDIEUTRI KHDT
	JOIN BUOIDIEUTRI BDT ON BDT.ID_KHDT_BDT = KHDT.ID_KHDT
	WHERE KHDT.ID_HOSOBENHNHAN = @ID_HOSOBENHNHAN	
END;
GO

-- Xem danh sách các thanh toán: nha sĩ 
CREATE OR ALTER PROCEDURE XEM_DS_THANHTOAN 
	@ID_HOSOBENHNHAN NCHAR(10)
AS
BEGIN
	SELECT * 
	FROM THONGTINTHANHTOAN
	WHERE ID_HOSOBENHNHAN = @ID_HOSOBENHNHAN
END;
GO

-- Báo cáo các điều trị trong ngày, theo từng bác sĩ.
CREATE OR ALTER PROCEDURE BAOCAO_DIEUTRI
	@NGAY DATE
AS
BEGIN
	SELECT ID_NHASI, 
		SUM(PHI) AS PHI_DIEU_TRI,
		SUM(THANHTOAN.TIENDATRA) AS TONG_TIEN_DA_THANH_TOAN
	FROM BUOIDIEUTRI BDT
	JOIN THONGTINTHANHTOAN THANHTOAN ON THANHTOAN.ID_THANHTOAN = BDT.ID_TT_BDT
	WHERE NGAYDIEUTRI = @NGAY
	GROUP BY ID_NHASI
END;
GO

-- Báo cáo các cuộc hẹn từ ngày đến ngày, theo từng bác sĩ
CREATE OR ALTER PROCEDURE BAOCAO_DIEUTRI
	@NGAY_BATDAU DATE,
	@NGAY_KETTHUC DATE
AS
BEGIN
	SELECT ID_NHASI, 
		COUNT(*) AS SO_CUOC_HEN
	FROM CUOCHEN
	WHERE CONVERT(DATE, THOIGIAN) BETWEEN @NGAY_BATDAU AND @NGAY_KETTHUC 
	GROUP BY ID_NHASI
END;