USE master
GO
IF DB_ID('QLPHONGKHAM_CSDLNC') IS NOT NULL
	DROP DATABASE QLPHONGKHAM_CSDLNC
GO --KẾT THÚC KHỐI LỆNH Ở TRÊN
CREATE DATABASE QLPHONGKHAM_CSDLNC
GO

USE QLPHONGKHAM_CSDLNC
GO

CREATE TABLE BENHNHAN
(
	ID_BENHNHAN NCHAR(10),
	TEN NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(3),-- ENUM(N'Nam',N'Nữ')
	DIACHI NVARCHAR(50),
	EMAIL NCHAR(20),
	SODIENTHOAI NCHAR(10),
	TONGTIENTHANHTOAN DECIMAL(18,2),
	TONGTIENDIEUTRI DECIMAL(18,2),
	THONGTIN NVARCHAR(500),
	TINHTRANG NVARCHAR(10),
	CHONGCHIDINH NVARCHAR(150),
	PRIMARY KEY(ID_BENHNHAN)
)
GO
CREATE TABLE CUOCHEN
(
	ID_HEN NCHAR(10),
	PHONG NVARCHAR(50),
	TINHTRANG NVARCHAR(11),
	THOIGIAN DATETIME,
	GHICHU NVARCHAR(50),
	ID_NHASI NCHAR(10),
	ID_TROKHAM NCHAR(10),
	ID_PHONGKHAM NCHAR(10),
	ID_BENHNHAN NCHAR(10),
	PRIMARY KEY(ID_HEN)
)
GO
CREATE TABLE THONGTINTHANHTOAN
(
	ID_THANHTOAN NCHAR(10),
	ID_BENHNHAN NCHAR(10),
	TIENDATRA DECIMAL (18,2),
	TIENTHOI DECIMAL(18,2),
	LOAITHANHTOAN NVARCHAR(8),--(N'Tiền mặt',N'Online'),
	GHICHU NVARCHAR(50),
	TONGTIENTHANHTOAN DECIMAL(18,2),
	PRIMARY KEY (ID_THANHTOAN)
)
GO 
CREATE TABLE RANG
(
	RANG NVARCHAR(10),
	PRIMARY KEY (RANG)
)
GO 
CREATE TABLE LOAIMAT
(
	LOAIMAT NVARCHAR(10),
	TENMAT NVARCHAR(20),
	PRIMARY KEY (LOAIMAT)
)
GO
CREATE TABLE QUANLYTHUOC
(
	ID_THUOC NCHAR(10),
	ID_PHONGKHAM NCHAR(10),
	SOLUONGTON INT,
	PRIMARY KEY(ID_THUOC, ID_PHONGKHAM)
)
GO 
CREATE TABLE DONTHUOC
(
	ID_DONTHUOC NCHAR(10),
	TINHTRANG NVARCHAR(7),--ENUM(N'XUẤT',N'ĐÃ XUẤT')
	PRIMARY KEY (ID_DONTHUOC)
)
GO 
CREATE TABLE LICHLAMVIEC
(
	ID_LICHLAMVIEC NCHAR(10),
	ID_NV_LLV NCHAR(10),
	NGAYTHANGNAM DATE,
	GIOBATDAU DATETIME,
	GIOKETTHUC DATETIME,
	PHONGKHAM NCHAR(10),
	PRIMARY KEY(ID_LICHLAMVIEC)
)
GO 
CREATE TABLE PHONGKHAM
(
	ID_PHONGKHAM NCHAR(10),
	DIACHIPK NVARCHAR(10),
	SDTPK NCHAR(10),
	PRIMARY KEY(ID_PHONGKHAM)
)
GO
CREATE TABLE BUOIDIEUTRI
(
	ID_BUOIDIEUTRI NCHAR(10),
	NGAYDIEUTRI DATE,
	MOTA NVARCHAR(50),
	PHI DECIMAL(18,2),
	ID_KHDT_BDT NCHAR(10),
	ID_TT_BDT NCHAR(10),
	ID_DONTHUOC NCHAR(10),
	ID_TROKHAM NCHAR(10),
	ID_NHASI NCHAR(10),
	PRIMARY KEY (ID_BUOIDIEUTRI)
)
GO
CREATE TABLE NHANVIEN
(
	ID_NHANVIEN NCHAR(10),
	TEN NVARCHAR(50),
	NGAYSINH DATE,
	DIACHI NVARCHAR(50),
	EMAIL NVARCHAR(20),
	SODIENTHOAI NCHAR(10),
	LOAINHANVIEN NVARCHAR(13) -- Quản trị viên, Nha sĩ, Trợ khám
	PRIMARY KEY (ID_NHANVIEN)
)
GO

CREATE TABLE DANHMUCDIEUTRI
(
	ID_DANHMUC NCHAR(10),
	TENDANHMUC NVARCHAR(30),
	PRIMARY KEY (ID_DANHMUC)
)
GO
CREATE TABLE TAIKHOAN
(
	DIENTHOAI NCHAR(10),
	MATKHAU NCHAR(20),
	PRIMARY KEY(DIENTHOAI)
)
GO
CREATE TABLE KEHOACHDIEUTRI
(
	ID_KHDT NCHAR(10),
	MOTA NVARCHAR(100),
	TINHTRANGDIEUTRI NVARCHAR(14), --ENUM(N'Kế hoạch',N'Đã hoàn thành',N'Đã hủy'),
	ID_BENHNHAN NCHAR(10),
	PRIMARY KEY (ID_KHDT)
)
GO
CREATE TABLE CHITIETDONTHUOC
(
	ID_DT_CT NCHAR(10),
	ID_T_CT NCHAR(10),
	SOLUONG INT,
	PRIMARY KEY (ID_DT_CT, ID_T_CT)
)
GO
CREATE TABLE THUOC
(
	ID_THUOC NCHAR(10),
	TEN_THUOC NVARCHAR(20),
	PHI DECIMAL(18,2),
	DONVITINH NVARCHAR(5), --ENUM(N'Hộp',N'Viên','mg','ml'),
	PRIMARY KEY (ID_THUOC)
)
GO
CREATE TABLE SUDUNGDIEUTRI
(
	ID_DIEUTRI NCHAR(10),
	ID_BUOIDIEUTRI NCHAR(10),
	RANG NVARCHAR(10),
	LOAIMAT NVARCHAR(10),
	PRIMARY KEY (ID_DIEUTRI,RANG,LOAIMAT,ID_BUOIDIEUTRI)
)
GO
CREATE TABLE DIEUTRI
(
	ID_DIEUTRI NCHAR(10),
	TENDIEUTRI NVARCHAR(30),
	ID_DMDT_DT NCHAR(10),
	PHI DECIMAL(18,2),
	PRIMARY KEY (ID_DIEUTRI)
)
GO


ALTER TABLE CUOCHEN ADD FOREIGN KEY(ID_NHASI) REFERENCES NHASI(ID_NHASI)
ALTER TABLE CUOCHEN ADD FOREIGN KEY(ID_TROKHAM) REFERENCES TROKHAM(ID_TROKHAM)
ALTER TABLE CUOCHEN ADD FOREIGN KEY(ID_PHONGKHAM) REFERENCES PHONGKHAM(ID_PHONGKHAM)
ALTER TABLE CUOCHEN ADD FOREIGN KEY(ID_BENHNHAN) REFERENCES BENHNHAN(ID_BENHNHAN)

ALTER TABLE QUANLYTHUOC ADD FOREIGN KEY(ID_PHONGKHAM) REFERENCES PHONGKHAM(ID_PHONGKHAM)
ALTER TABLE QUANLYTHUOC ADD FOREIGN KEY(ID_THUOC) REFERENCES THUOC(ID_THUOC)

ALTER TABLE LICHLAMVIEC ADD FOREIGN KEY(ID_NV_LLV) REFERENCES NHANVIEN(ID_NHANVIEN)
ALTER TABLE LICHLAMVIEC ADD FOREIGN KEY(PHONGKHAM) REFERENCES PHONGKHAM(ID_PHONGKHAM)

ALTER TABLE BUOIDIEUTRI ADD FOREIGN KEY(ID_KHDT_BDT) REFERENCES KEHOACHDIEUTRI(ID_KHDT)
ALTER TABLE BUOIDIEUTRI ADD FOREIGN KEY(ID_TT_BDT) REFERENCES THONGTINTHANHTOAN(ID_THANHTOAN)
ALTER TABLE BUOIDIEUTRI ADD FOREIGN KEY(ID_DONTHUOC) REFERENCES DONTHUOC(ID_DONTHUOC)
ALTER TABLE BUOIDIEUTRI ADD FOREIGN KEY(ID_TROKHAM) REFERENCES TROKHAM(ID_TROKHAM)
ALTER TABLE BUOIDIEUTRI ADD FOREIGN KEY(ID_NHASI) REFERENCES NHASI(ID_NHASI)

ALTER TABLE QUANTRIVIEN ADD FOREIGN KEY(ID_QUANTRIVIEN) REFERENCES NHANVIEN(ID_NHANVIEN)
ALTER TABLE TROKHAM ADD FOREIGN KEY(ID_TROKHAM) REFERENCES NHANVIEN(ID_NHANVIEN)
ALTER TABLE NHASI ADD FOREIGN KEY(ID_NHASI) REFERENCES NHANVIEN(ID_NHANVIEN)
ALTER TABLE NHANVIEN ADD FOREIGN KEY(SODIENTHOAI) REFERENCES TAIKHOAN(DIENTHOAI)
ALTER TABLE BENHNHAN ADD FOREIGN KEY(SODIENTHOAI) REFERENCES TAIKHOAN(DIENTHOAI)

ALTER TABLE DIEUTRI ADD FOREIGN KEY (ID_DMDT_DT) REFERENCES DANHMUCDIEUTRI(ID_DANHMUC)

ALTER TABLE KEHOACHDIEUTRI ADD FOREIGN KEY(ID_BENHNHAN) REFERENCES BENHNHAN(ID_BENHNHAN)
ALTER TABLE CHITIETDONTHUOC ADD FOREIGN KEY(ID_DT_CT) REFERENCES DONTHUOC(ID_DONTHUOC)
ALTER TABLE CHITIETDONTHUOC ADD FOREIGN KEY(ID_T_CT) REFERENCES THUOC(ID_THUOC)

ALTER TABLE SUDUNGDIEUTRI ADD FOREIGN KEY(ID_DIEUTRI) REFERENCES DIEUTRI(ID_DIEUTRI)
ALTER TABLE SUDUNGDIEUTRI ADD FOREIGN KEY(RANG) REFERENCES RANG(RANG)
ALTER TABLE SUDUNGDIEUTRI ADD FOREIGN KEY(ID_BUOIDIEUTRI) REFERENCES BUOIDIEUTRI(ID_BUOIDIEUTRI)
ALTER TABLE SUDUNGDIEUTRI ADD FOREIGN KEY(LOAIMAT) REFERENCES LOAIMAT(LOAIMAT)

ALTER TABLE THONGTINTHANHTOAN ADD FOREIGN KEY(ID_BENHNHAN) REFERENCES BENHNHAN(ID_BENHNHAN)
