USE QLPHONGKHAM_CSDLNC; 
GO
-- XEM PHÒNG KHÁM
CREATE OR ALTER PROCEDURE XEM_PHONGKHAM
AS
BEGIN
	SELECT * FROM PHONGKHAM
END
GO

EXEC XEM_PHONGKHAM
GO
-- TẠO PHÒNG KHÁM 
CREATE OR ALTER PROCEDURE TAO_PHONGKHAM
	@DIACHIPK NVARCHAR(50), 
	@SDTPK CHAR(10)
AS
BEGIN
	INSERT INTO PHONGKHAM(DIACHIPK, SDTPK)
	VALUES (@DIACHIPK, @SDTPK)
END
GO
-- XOÁ PHÒNG KHÁM
CREATE OR ALTER PROCEDURE XOA_PHONGKHAM
	@ID_PHONGKHAM TINYINT
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM PHONGKHAM WHERE ID_PHONGKHAM = @ID_PHONGKHAM)
	BEGIN
		RAISERROR(N'PHÒNG KHÁM KO TỒN TẠI', 16, 1)
		RETURN
	END
	DELETE PHONGKHAM WHERE ID_PHONGKHAM = @ID_PHONGKHAM
END
GO
-- QUẢN LÝ THUỐC
CREATE OR ALTER PROCEDURE TAO_QUANLY_THUOC
	@ID_PHONGKHAM TINYINT, 
	@ID_THUOC INT, 
	@SOLUONGTON INT
AS
BEGIN
	IF EXISTS(SELECT 1 FROM QUANLY_THUOC WHERE ID_PHONGKHAM = @ID_PHONGKHAM 
			AND ID_THUOC = @ID_THUOC)
	BEGIN
		RAISERROR(N'ĐÃ TỒN TẠI THUỐC NÀY TẠI PHÒNG KHÁM', 16, 1)
		RETURN 
	END

	INSERT INTO QUANLY_THUOC(ID_PHONGKHAM, ID_THUOC, SOLUONGTON)
	VALUES(@ID_PHONGKHAM, @ID_THUOC, @SOLUONGTON)
END
GO
-- TEST TẠO QUẢN LÝ THUỐC
EXEC TAO_QUANLY_THUOC 1, 1, 10

-- CẬP NHẬT SỐ LƯỢNG QUẢN LÝ THUỐC CỦA PHÒNG KHÁM
CREATE OR ALTER PROCEDURE CAPNHAT_QUANLY_THUOC
	@ID_PHONGKHAM TINYINT,
	@ID_THUOC INT,
	@SOLUONGTON INT
AS
BEGIN
	UPDATE QUANLY_THUOC
	SET SOLUONGTON = @SOLUONGTON
	WHERE ID_PHONGKHAM = @ID_PHONGKHAM AND ID_THUOC = @ID_THUOC
	IF @@ROWCOUNT = 0
	BEGIN
		RAISERROR('LOI HE THONG', 16, 1)
		RETURN
	END
END
GO
-- test
EXEC CAPNHAT_QUANLY_THUOC 1, 1, 20

-- XEM QUẢN LÝ THUỐC CỦA 1 PHÒNG 
CREATE OR ALTER PROCEDURE XEM_QUANLY_THUOC_PHONGKHAM 
	@ID_PHONGKHAM INT
AS
BEGIN
	SELECT QL.ID_PHONGKHAM, QL.ID_THUOC, TH.TEN_THUOC, SOLUONGTON
	FROM QUANLY_THUOC QL
	JOIN THUOC TH ON TH.ID_THUOC = QL.ID_THUOC
	WHERE ID_PHONGKHAM = @ID_PHONGKHAM
END
EXEC XEM_QUANLY_THUOC_PHONGKHAM 1

select * from TAIKHOAN