use QLPHONGKHAM_CSDLNC
go

CREATE OR ALTER TRIGGER TRG_THEMCTDTR ON CHITIET_DIEUTRI AFTER INSERT AS
BEGIN 
	UPDATE KEHOACH_DIEUTRI
	SET TONG_CHIPHI = TONG_CHIPHI + (
		SELECT dt.PHI 
		FROM inserted i, DIEUTRI dt
		WHERE i.ID_DIEUTRI = dt.ID_DIEUTRI )
	WHERE ID_KEHOACH_DIEUTRI = (SELECT I.ID_KEHOACH_DIEUTRI FROM  inserted I)

END
GO

CREATE OR ALTER TRIGGER TRG_THEMCTDT ON CHITIET_DONTHUOC AFTER INSERT AS
BEGIN 
	UPDATE DONTHUOC
		SET TONG_CHIPHI = TONG_CHIPHI + (
		SELECT i.SOLUONG * T.PHI
		FROM inserted i, THUOC T
		WHERE i.ID_DONTHUOC = ID_DONTHUOC AND i.ID_THUOC = T.ID_THUOC)
	WHERE ID_DONTHUOC = ( select i.ID_DONTHUOC from inserted i)
END
go

CREATE OR ALTER TRIGGER TRG_UPDATETHONGTINTHANHTOAN ON THONGTIN_THANHTOAN AFTER UPDATE AS
BEGIN
	UPDATE THONGTIN_THANHTOAN 
		SET TIENTHOI = TIENDATRA - 
			(SELECT TONGTIENTHANHTOAN 
			FROM inserted I
			WHERE I.ID_THONGTIN_THANHTOAN = ID_THONGTIN_THANHTOAN)
		WHERE ID_THONGTIN_THANHTOAN = (SELECT ID_THONGTIN_THANHTOAN FROM inserted )
END
GO

CREATE OR ALTER TRIGGER TRG_UPDATETHONGTINTHANHTOAN_DONTHUOC ON THONGTIN_THANHTOAN_DONTHUOC AFTER UPDATE AS
BEGIN
	UPDATE THONGTIN_THANHTOAN_DONTHUOC
		SET TIENTHOI = TIENDATRA -
			(SELECT TONGTIENTHANHTOAN 
			FROM inserted I
			WHERE I.ID_THONGTIN_THANHTOAN_DONTHUOC = ID_THONGTIN_THANHTOAN_DONTHUOC)
		WHERE ID_THONGTIN_THANHTOAN_DONTHUOC = (SELECT ID_THONGTIN_THANHTOAN_DONTHUOC FROM inserted )

END
GO

CREATE OR ALTER TRIGGER TRG_UPDATEDONTHUOC ON DONTHUOC AFTER UPDATE AS
BEGIN
	UPDATE THONGTIN_THANHTOAN_DONTHUOC
		SET TONGTIENTHANHTOAN = TONGTIENTHANHTOAN +
			(SELECT I.TONG_CHIPHI
			FROM inserted I WHERE I.ID_DONTHUOC = ID_DONTHUOC) -
			(SELECT D.TONG_CHIPHI 
			FROM deleted D WHERE D.ID_DONTHUOC = ID_DONTHUOC)
		WHERE ID_DONTHUOC = (SELECT ID_DONTHUOC FROM inserted)
END 
GO

CREATE OR ALTER TRIGGER TRG_UPDATEKEHOACHDIEUTRI ON KEHOACH_DIEUTRI AFTER UPDATE AS
BEGIN
	UPDATE THONGTIN_THANHTOAN
		SET TONGTIENTHANHTOAN = TONGTIENTHANHTOAN +
			(SELECT I.TONG_CHIPHI
			FROM inserted I WHERE I.ID_KEHOACH_DIEUTRI = ID_KEHOACH_DIEUTRI) -
			(SELECT D.TONG_CHIPHI 
			FROM deleted D WHERE D.ID_KEHOACH_DIEUTRI = ID_KEHOACH_DIEUTRI)
		WHERE ID_KEHOACH_DIEUTRI = (SELECT ID_KEHOACH_DIEUTRI FROM inserted)
END 
GO

CREATE OR ALTER TRIGGER TRG_THEMLICHLAMVIEC ON LICHLAMVIEC AFTER INSERT AS
BEGIN 
	UPDATE LICHLAMVIEC
		SET GIOKETTHUC = (
		SELECT DATEADD(HOUR, 4, i.GIOBATDAU)
		FROM inserted i
		WHERE i.ID_LICHLAMVIEC = ID_LICHLAMVIEC)
	WHERE ID_LICHLAMVIEC = ( select i.ID_LICHLAMVIEC from inserted i)
END
go	
