USE QLPHONGKHAM_CSDLNC;
GO

-- TÌM BỆNH NHÂN BẰNG SỐ ĐIỆN THOẠI
EXEC TIM_BENHNHAN_BANG_SDT '099'

-- TÌM NHA SĨ RẢNH
EXEC TIM_NHASI_RANH 1, '2023-08-10 08:00'
-- THÊM KẾ HOẠCH ĐIỀU TRỊ
DECLARE @OUTPUT_KEHOACH_DIEUTRI INT;
EXEC THEM_KEHOACH_DIEUTRI '', '', 1, @OUTPUT_KEHOACH_DIEUTRI
SELECT TOP 1 * FROM KEHOACH_DIEUTRI ORDER BY ID_KEHOACH_DIEUTRI DESC
-- THÊM CHI TIẾT ĐIỀU TRỊ
-- THÊM THÔNG TIN THANH TOÁN ĐIỀU TRỊ
EXEC THEM_CHITIET_DIEUTRI 1, 1, 3, 'L'