USE QLPHONGKHAM_CSDLNC; 
GO

-- XEM DANH SÁCH CÁC THANH TOÁN	
CREATE OR ALTER PROCEDURE XEM_DS_THANHTOAN
	@ID_BENHNHAN INT
AS
BEGIN
	SELECT TT.ID_THONGTIN_THANHTOAN, 
	TT.TIENDATRA, TT.TIENTHOI, TT.LOAITHANHTOAN,
	TT.GHICHU, TT.TONGTIENTHANHTOAN,
	KHDT.CHANDOAN, KHDT.NOIDUNG,
	KHDT.TINHTRANGDIEUTRI, KHDT.TONG_CHIPHI
	FROM THONGTIN_THANHTOAN TT
	JOIN KEHOACH_DIEUTRI KHDT ON KHDT.ID_KEHOACH_DIEUTRI = TT.ID_KEHOACH_DIEUTRI
	WHERE KHDT.ID_BENHNHAN = @ID_BENHNHAN
END
GO

EXEC XEM_DS_THANHTOAN 1
GO
-- TẠO THANH TOÁN KẾ HOẠCH ĐIỀU TRỊ
CREATE OR ALTER PROCEDURE TAO_THONGTIN_THANHTOAN
	@ID_BENHNHAN INT,
	@TIENDATRA BIGINT,
	@TIENTHOI BIGINT,
	@LOAITHANHTOAN NVARCHAR(8),--(N'Tiền mặt',N'Online'),
	@GHICHU NVARCHAR(50),
	@TONGTIENTHANHTOAN BIGINT,
	@ID_KEHOACH_DIEUTRI INT
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM KEHOACH_DIEUTRI WHERE ID_BENHNHAN = @ID_BENHNHAN)
	BEGIN
		RAISERROR(N'BỆNH NHÂN CHƯA CÓ KẾ HOẠCH ĐIỀU TRỊ ĐỂ TRẢ', 16, 1)
		RETURN
	END; 

	INSERT INTO THONGTIN_THANHTOAN
	(ID_BENHNHAN, TIENDATRA, TIENTHOI, LOAITHANHTOAN, GHICHU, TONGTIENTHANHTOAN, ID_KEHOACH_DIEUTRI)
	VALUES (@ID_BENHNHAN, @TIENDATRA, @TIENTHOI, @LOAITHANHTOAN, @GHICHU, @TONGTIENTHANHTOAN, @ID_KEHOACH_DIEUTRI)
	
	-- CẬP NHẬT TỔNG TIỀN THANH TOÁN VÀ TỔNG TIỀN CHƯA THANH TOÁN CỦA BỆNH NHÂN
	UPDATE BENHNHAN
	SET TONGTIENTHANHTOAN = TONGTIENTHANHTOAN + @TONGTIENTHANHTOAN,
	TONTIENCHUATHANHTOAN = TONGTIENCHUATHANHTOAN - @TONGTIENTHANHTOAN
	WHERE ID_BENHNHAN = @ID_BENHNHAN
END; 

EXEC TAO_THONGTIN_THANHTOAN 1, 20000, 0, N'ONLINE', '', 20000, 4
GO

-- XEM CÁC THANH TOÁN CHƯA TRẢ
CREATE OR ALTER PROCEDURE XEM_THANHTOAN_CHUATRA
    @ID_BENHNHAN INT
AS
BEGIN
	-- THANH TOÁN CHƯA TRẢ CỦA KẾ HOẠCH ĐIỀU TRỊ
    SELECT KHDT.ID_KEHOACH_DIEUTRI, 
		   KHDT.TONG_CHIPHI - SUM(TT.TIENDATRA) AS TIEN_CONTHIEU
    FROM KEHOACH_DIEUTRI KHDT 
    JOIN THONGTIN_THANHTOAN TT ON KHDT.ID_KEHOACH_DIEUTRI = TT.ID_KEHOACH_DIEUTRI
    WHERE KHDT.ID_BENHNHAN = @ID_BENHNHAN
	GROUP BY KHDT.ID_KEHOACH_DIEUTRI, KHDT.TONG_CHIPHI
	HAVING KHDT.TONG_CHIPHI - SUM(TT.TIENDATRA) > 0
	

	-- THANH TOÁN CHƯA TRẢ CỦA ĐƠN THUỐC
	SELECT DT.ID_DONTHUOC, DT.TONG_CHIPHI
    FROM DONTHUOC DT
    JOIN THONGTIN_THANHTOAN_DONTHUOC TT ON DT.ID_DONTHUOC = TT.ID_DONTHUOC
    WHERE DT.ID_BENHNHAN = @ID_BENHNHAN
END;
GO

EXEC XEM_THANHTOAN_CHUATRA 32

-- XEM DANH SÁCH THANH TOÁN ĐƠN THUỐC => TRANG XEM THÔNG TIN THANH TOÁN ĐƠN THUỐC
CREATE OR ALTER PROCEDURE XEM_DS_THANHTOAN_DONTHUOC
	@ID_BENHNHAN INT
AS
BEGIN
	SELECT TT.ID_THONGTIN_THANHTOAN_DONTHUOC, 
	TT.TIENDATRA, TT.TIENTHOI, TT.LOAITHANHTOAN,
	TT.GHICHU, TT.TONGTIENTHANHTOAN,
	DT.ID_DONTHUOC, DT.daXuat, CTDT.*
	FROM THONGTIN_THANHTOAN_DONTHUOC TT
	JOIN DONTHUOC DT ON DT.ID_DONTHUOC= TT.ID_DONTHUOC
	JOIN CHITIET_DONTHUOC CTDT ON CTDT.ID_DONTHUOC = DT.ID_DONTHUOC
	WHERE TT.ID_BENHNHAN = @ID_BENHNHAN
END
GO

-- TẠO THÔNG TIN THANH TOÁN ĐƠN THUỐC
CREATE OR ALTER PROCEDURE TAO_THONGTIN_THANHTOAN_DONTHUOC
	@ID_BENHNHAN INT,
	@TIENDATRA BIGINT,
	@TIENTHOI BIGINT,
	@LOAITHANHTOAN NVARCHAR(8),--(N'Tiền mặt',N'Online'),
	@GHICHU NVARCHAR(50),
	@TONGTIENTHANHTOAN BIGINT,
	@ID_DONTHUOC INT
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM DONTHUOC WHERE ID_BENHNHAN = @ID_BENHNHAN)
	BEGIN
		RAISERROR(N'BỆNH NHÂN CHƯA CÓ ĐƠN THUỐC NÀY ĐỂ TRẢ', 16, 1)
		RETURN
	END; 
	
	IF EXISTS(SELECT 1 FROM THONGTIN_THANHTOAN_DONTHUOC WHERE ID_DONTHUOC = @ID_DONTHUOC)
	BEGIN
		RAISERROR(N'ĐƠN THUỐC ĐÃ THANH TOÁN', 16, 1)
		RETURN
	END; 

	INSERT INTO THONGTIN_THANHTOAN_DONTHUOC
	(ID_BENHNHAN, TIENDATRA, TIENTHOI, LOAITHANHTOAN, GHICHU, TONGTIENTHANHTOAN, ID_DONTHUOC)
	VALUES (@ID_BENHNHAN, @TIENDATRA, @TIENTHOI, @LOAITHANHTOAN, @GHICHU, @TONGTIENTHANHTOAN, @ID_DONTHUOC)

	-- CẬP NHẬT TỔNG TIỀN THANH TOÁN VÀ TỔNG TIỀN CHƯA THANH TOÁN CỦA BỆNH NHÂN
	UPDATE BENHNHAN
	SET TONGTIENTHANHTOAN = TONGTIENTHANHTOAN + @TONGTIENTHANHTOAN,
	TONGTIENCHUATHANHTOAN = TONGTIENCHUATHANHTOAN - @TONGTIENTHANHTOAN
	WHERE ID_BENHNHAN = @ID_BENHNHAN
END; 
