USE QLPHONGKHAM_CSDLNC
GO

-- XEM DANH SÁCH THUỐC
CREATE OR ALTER PROCEDURE XEM_DS_THUOC
AS
BEGIN
	SELECT * 
	FROM THUOC
END; 
GO

EXEC XEM_DS_THUOC

-- THÊM THUỐC
CREATE OR ALTER PROCEDURE THEM_THUOC
	@TEN_THUOC NVARCHAR(20),
	@PHI INT
AS
BEGIN
	INSERT INTO THUOC(TEN_THUOC, PHI)
	VALUES (@TEN_THUOC, @PHI)
END;
GO

EXEC THEM_THUOC N'MA TUÝ', 30000, 'MG'

-- XOÁ THUỐC
CREATE OR ALTER PROCEDURE XOA_THUOC
	@ID_THUOC INT
AS
BEGIN
	DELETE THUOC WHERE ID_THUOC = @ID_THUOC
END;
GO

EXEC XOA_THUOC 1
GO

-- CẬP NHẬT THUỐC
CREATE OR ALTER PROCEDURE CAPNHAT_THUOC
	@ID_THUOC INT,
	@TEN_THUOC NVARCHAR(20),
	@PHI INT
AS 
BEGIN
	IF NOT EXISTS(SELECT 1 FROM THUOC WHERE ID_THUOC = @ID_THUOC)
	BEGIN
		RAISERROR(N'KO TỒN TẠI THUỐC NÀY', 16, 1)
		RETURN
	END;
	
	UPDATE THUOC
	SET TEN_THUOC = @TEN_THUOC,
		PHI = @PHI	
	WHERE ID_THUOC = @ID_THUOC
END
GO
EXEC CAPNHAT_THUOC 3, N'VITAMIN C', 35000, 'MG'

-- THÊM ĐƠN THUỐC
CREATE OR ALTER PROCEDURE THEM_DONTHUOC
	@ID_BENHNHAN INT,
	@BACSIDIEUTRI INT,
	@GHICHU NVARCHAR(50)
AS
BEGIN
	-- KIEM TRA CO PHAI nha si KO
	IF NOT EXISTS(SELECT 1 FROM NHANVIEN WHERE ID_NHANVIEN = @BACSIDIEUTRI AND LOAINHANVIEN = N'Nha sĩ')
	BEGIN
		RAISERROR(N'KHÔNG PHẢI BÁC SĨ', 16, 1)
		RETURN
	END
	INSERT INTO DONTHUOC(ID_BENHNHAN, GHICHU, BACSIDIEUTRI)
	VALUES (@ID_BENHNHAN, @GHICHU, @BACSIDIEUTRI)
END;

-- THÊM CHI TIẾT ĐƠN THUỐC
CREATE OR ALTER PROCEDURE THEM_CHITIET_DONTHUOC
	@ID_DONTHUOC INT,
	@ID_THUOC INT, 
	@SOLUONG INT,
	@ID_PHONGKHAM INT
AS
BEGIN
	-- KIỂM TRA CÓ ĐỦ SỐ LƯỢNG THUỐC CỦA PHÒNG KHÁM
	IF EXISTS(SELECT 1 FROM QUANLY_THUOC WHERE ID_PHONGKHAM = @ID_PHONGKHAM 
			AND SOLUONGTON < @SOLUONG)
	BEGIN
		RAISERROR(N'KHÔNG ĐỦ SỐ LƯỢNG THUỐC', 16, 1)
		RETURN
	END

	INSERT INTO CHITIET_DONTHUOC(ID_DONTHUOC, ID_THUOC, SOLUONG)
	VALUES (@ID_DONTHUOC, @ID_THUOC, @SOLUONG)
	-- CẬP NHẬT PHÍ CHO ĐƠN THUỐC
	UPDATE DONTHUOC
	SET TONG_CHIPHI = TONG_CHIPHI + @SOLUONG * (SELECT PHI FROM THUOC WHERE ID_THUOC = @ID_THUOC)
	WHERE ID_DONTHUOC = @ID_DONTHUOC

	-- CẬP NHẬT SỐ LƯỢNG TỒN CỦA PHÒNG KHÁM
	UPDATE QUANLY_THUOC
	SET SOLUONGTON = SOLUONGTON - @SOLUONG
	WHERE ID_PHONGKHAM = @ID_PHONGKHAM AND ID_THUOC = @ID_THUOC
END

INSERT INTO DONTHUOC(ID_BENHNHAN)
VALUES (1)
SELECT * FROM DONTHUOC
EXEC THEM_CHITIET_DONTHUOC 1, 3, 2
EXEC THEM_CHITIET_DONTHUOC 1, 3, 2
GO

-- XOÁ CHI TIẾT ĐƠN THUỐC
CREATE OR ALTER XOA_CHITIET_DONTHUOC
	@ID_DONTHUOC INT, 
	@ID_THUOC INT
AS
BEGIN
	DECLARE @SOLUONG INT;
	SELECT @SOLUONG = (SELECT SOLUONG FROM CHITIET_DONTHUOC WHERE ID_DONTHUOC = @ID_DONTHUOC AND ID_THUOC = @ID_THUOC)
	-- XOÁ CHI TIẾT ĐƠN THUỐC
	DELETE CHITIET_DONTHUOC WHERE ID_DONTHUOC = @ID_DONTHUOC AND ID_THUOC = @ID_THUOC
	-- TRỪ TỔNG CHI PHÍ CỦA ĐƠN THUỐC
	UPDATE DONTHUOC
	SET TONG_CHIPHI = TONG_CHIPHI - @SOLUONG * (SELECT PHI FROM THUOC WHERE ID_THUOC = @ID_THUOC)
	WHERE ID_DONTHUOC = @ID_DONTHUOC
END
GO