USE QLPHONGKHAM_CSDLNC; 
GO 

SELECT 
    TableName = t.name,
    IndexName = ind.name,
    IndexType = ind.type_desc,
    ic.index_column_id,
    ColumnName = col.name
FROM 
    sys.indexes ind
INNER JOIN 
    sys.index_columns ic ON ind.object_id = ic.object_id AND ind.index_id = ic.index_id
INNER JOIN 
    sys.columns col ON ic.object_id = col.object_id AND ic.column_id = col.column_id
INNER JOIN 
    sys.tables t ON ind.object_id = t.object_id
WHERE 
    t.name = 'KEHOACH_DIEUTRI' 
    AND ind.is_primary_key = 0 -- Exclude primary keys
    AND ind.is_unique_constraint = 0 -- Exclude unique constraints
ORDER BY 
    t.name, ind.name, ic.index_column_id;
GO

CREATE NONCLUSTERED INDEX IX_KHDT_ID_BENHNHAN ON KEHOACH_DIEUTRI(ID_BENHNHAN)

DROP INDEX IX_KHDT_ID_BENHNHA ON KEHOACH_DIEUTRI
-- INSERT 100,000 KEHOACHDIEUTRI ĐỂ TEST ĐỘ HIỆU QUẢ CỦA INDEX
-- THANH TOÁN CHƯA TRẢ CỦA KẾ HOẠCH ĐIỀU TRỊ
	SELECT KHDT.ID_KEHOACH_DIEUTRI, 
	(CASE WHEN COALESCE(SUM(TT.TIENDATRA), 0) = 0 THEN KHDT.TONG_CHIPHI
	ELSE  KHDT.TONG_CHIPHI - SUM(TT.TIENDATRA) END) AS TIEN_CONTHIEU
    FROM KEHOACH_DIEUTRI KHDT 
    LEFT JOIN THONGTIN_THANHTOAN TT ON KHDT.ID_KEHOACH_DIEUTRI = TT.ID_KEHOACH_DIEUTRI
    WHERE KHDT.ID_BENHNHAN = 240
	GROUP BY KHDT.ID_KEHOACH_DIEUTRI, KHDT.TONG_CHIPHI

-- THANH TOÁN CHƯA TRẢ CỦA ĐƠN THUỐC
	SELECT DT.ID_DONTHUOC, DT.TONG_CHIPHI
    FROM DONTHUOC DT
    LEFT JOIN THONGTIN_THANHTOAN_DONTHUOC TT ON DT.ID_DONTHUOC = TT.ID_DONTHUOC
    WHERE DT.ID_BENHNHAN = 100 
	AND TT.ID_THONGTIN_THANHTOAN_DONTHUOC IS NULL

CREATE OR ALTER PROCEDURE XEM_THANHTOAN_CHUATRA_TOIUU
    @ID_BENHNHAN INT
AS
BEGIN
	-- THANH TOÁN CHƯA TRẢ CỦA KẾ HOẠCH ĐIỀU TRỊ
    SELECT KHDT.ID_KEHOACH_DIEUTRI,
	(CASE WHEN COALESCE(SUM(TT.TIENDATRA), 0) = 0 THEN KHDT.TONG_CHIPHI
	ELSE KHDT.TONG_CHIPHI - SUM(TT.TIENDATRA) END) AS TIEN_CHUATRA
    FROM KEHOACH_DIEUTRI KHDT 
    LEFT JOIN THONGTIN_THANHTOAN TT ON KHDT.ID_KEHOACH_DIEUTRI = TT.ID_KEHOACH_DIEUTRI
    WHERE KHDT.ID_BENHNHAN = @ID_BENHNHAN
	GROUP BY KHDT.ID_KEHOACH_DIEUTRI, KHDT.TONG_CHIPHI

	-- THANH TOÁN CHƯA TRẢ CỦA ĐƠN THUỐC
	--SELECT DT.ID_DONTHUOC, DT.TONG_CHIPHI
 --   FROM DONTHUOC DT
 --   LEFT JOIN THONGTIN_THANHTOAN_DONTHUOC TT ON DT.ID_DONTHUOC = TT.ID_DONTHUOC
 --   WHERE DT.ID_BENHNHAN = @ID_BENHNHAN 
	--AND TT.ID_THONGTIN_THANHTOAN_DONTHUOC IS NULL
END;
GO

SET STATISTICS TIME ON; 
exec XEM_THANHTOAN_CHUATRA_TOIUU 766
SET STATISTICS TIME OFF;
