USE QLPHONGKHAM_CSDLNC;
GO

CREATE NONCLUSTERED INDEX IX_GIOBATDAU ON LICHLAMVIEC (GIOBATDAU, GIOKETTHUC) INCLUDE(ID_NHANVIEN);
CREATE INDEX IX_GIOKETTHUC ON LICHLAMVIEC (GIOKETTHUC); 
CREATE INDEX IX_ID_NHANVIEN ON LICHLAMVIEC (ID_NHANVIEN);

DROP INDEX IX_GIOBATDAU ON LICHLAMVIEC;
DROP INDEX IX_GIOKETTHUC ON LICHLAMVIEC;
DROP INDEX IX_ID_NHANVIEN ON LICHLAMVIEC;

SET STATISTICS TIME ON;
DECLARE @ID_BENHNHAN INT = 1; 
DECLARE @GIO_BATDAU DATETIME = '2023-01-03 06:00'; 
DECLARE @GIO_KETTHUC DATETIME = DATEADD(HOUR, 1, @GIO_BATDAU);

SELECT 
    TableName = t.name,
    IndexName = ind.name,
    IndexType = ind.type_desc,
    ic.index_column_id,
    ColumnName = col.name
FROM 
    sys.indexes ind
INNER JOIN 
    sys.index_columns ic ON ind.object_id = ic.object_id AND ind.index_id = ic.index_id
INNER JOIN 
    sys.columns col ON ic.object_id = col.object_id AND ic.column_id = col.column_id
INNER JOIN 
    sys.tables t ON ind.object_id = t.object_id
WHERE 
    t.name = 'LICHLAMVIEC' -- Replace 'YourTableName' with your table name
    AND ind.is_primary_key = 0 -- Exclude primary keys
    AND ind.is_unique_constraint = 0 -- Exclude unique constraints
ORDER BY 
    t.name, ind.name, ic.index_column_id;

EXEC DBO.XEM_INDEX_BANG 'LICHLAMVIEC'

-- Use @GIO_KETTHUC directly in the query
WITH DS_ID_NHASI AS (
	SELECT ID_NHANVIEN
	FROM LICHLAMVIEC
	WHERE GIOBATDAU <= @GIO_BATDAU AND GIOKETTHUC >= @GIO_KETTHUC
), 
	DS_NHASI AS (
    SELECT NV.ID_NHANVIEN, NV.TEN
    FROM NHANVIEN NV 
    JOIN DS_ID_NHASI DS ON DS.ID_NHANVIEN = NV.ID_NHANVIEN 
)

	SELECT DS.ID_NHANVIEN, DS.TEN, 1 AS DA_KHAM
    FROM DS_NHASI DS WHERE DS.ID_NHANVIEN IN 
	(SELECT CH.ID_NHASI FROM CUOCHEN CH WHERE CH.ID_BENHNHAN = @ID_BENHNHAN)
	UNION ALL
	SELECT DS.ID_NHANVIEN, DS.TEN, 0 AS DA_KHAM
	FROM DS_NHASI DS WHERE DS.ID_NHANVIEN NOT IN
	(SELECT CH.ID_NHASI FROM CUOCHEN CH WHERE CH.ID_BENHNHAN = @ID_BENHNHAN)
SET STATISTICS TIME OFF;  

-- PROCEDURE TIM_NHASI_RANH SAU KHI TỐI ƯU TRUY VẤN
CREATE OR ALTER PROCEDURE TIM_NHASI_RANH_TOIUU
	@ID_BENHNHAN INT,
    @GIO_BATDAU DATETIME
AS
BEGIN
	DECLARE @GIO_KETTHUC DATETIME = DATEADD(HOUR, 1, @GIO_BATDAU);

    WITH DS_ID_NHASI AS (
	SELECT ID_NHANVIEN
	FROM LICHLAMVIEC
	WHERE GIOBATDAU <= @GIO_BATDAU AND GIOKETTHUC >= @GIO_KETTHUC
	), 
	DS_NHASI AS (
    SELECT NV.ID_NHANVIEN, NV.TEN
    FROM NHANVIEN NV 
    JOIN DS_ID_NHASI DS ON DS.ID_NHANVIEN = NV.ID_NHANVIEN 
	WHERE NV.LOAINHANVIEN = N'Nha sĩ'
	)

	SELECT DS.ID_NHANVIEN, DS.TEN, 1 AS DA_KHAM
    FROM DS_NHASI DS WHERE DS.ID_NHANVIEN IN 
	(SELECT CH.ID_NHASI FROM CUOCHEN CH WHERE CH.ID_BENHNHAN = @ID_BENHNHAN)
	UNION ALL
	SELECT DS.ID_NHANVIEN, DS.TEN, 0 AS DA_KHAM
	FROM DS_NHASI DS WHERE DS.ID_NHANVIEN NOT IN
	(SELECT CH.ID_NHASI FROM CUOCHEN CH WHERE CH.ID_BENHNHAN = @ID_BENHNHAN)
END;
GO

SET STATISTICS TIME ON; 
EXEC TIM_NHASI_RANH_TOIUU 1, '2023-05-20 12:00'
SET STATISTICS TIME OFF;