USE QLPHONGKHAM_CSDLNC
GO

CREATE OR ALTER TRIGGER TRG_THEM_CHITIET_DIEUTRI
ON CHITIET_DIEUTRI
AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @TONGPHI INT;
	DECLARE @NGAYHOMNAY DATE = GETDATE();
	DECLARE @ID_KEHOACH_DIEUTRI INT = (SELECT TOP 1 I.ID_KEHOACH_DIEUTRI FROM inserted I)

	SELECT @TONGPHI = (SELECT SUM(DT.PHI) FROM inserted I 
	JOIN DIEUTRI DT ON DT.ID_DIEUTRI = I.ID_DIEUTRI)

	IF NOT EXISTS(SELECT 1 FROM THONGTIN_THANHTOAN WHERE ID_KEHOACH_DIEUTRI = @ID_KEHOACH_DIEUTRI
					AND NGAYTAO_CAC_CHITIET_DIEUTRI = @NGAYHOMNAY)
	BEGIN
		INSERT INTO THONGTIN_THANHTOAN(ID_KEHOACH_DIEUTRI, TIENDATRA, TIENTHOI, TONGTIENTHANHTOAN, NGAYTAO_CAC_CHITIET_DIEUTRI, LOAITHANHTOAN)
		VALUES (@ID_KEHOACH_DIEUTRI, 0, 0, 0, @NGAYHOMNAY, 'Online')
	END

	-- CẬP NHẬT TỔNG CHI PHÍ CỦA KẾ HOẠCH ĐIỀU TRỊ
	UPDATE KEHOACH_DIEUTRI
	SET TONG_CHIPHI = TONG_CHIPHI + @TONGPHI
	WHERE ID_KEHOACH_DIEUTRI = @ID_KEHOACH_DIEUTRI

	-- CẬP NHẬT TỔNG CHI PHÍ CỦA THÔNG TIN THANH TOÁN
	UPDATE THONGTIN_THANHTOAN
	SET TONGTIENTHANHTOAN = TONGTIENTHANHTOAN + @TONGPHI
	WHERE ID_KEHOACH_DIEUTRI = @ID_KEHOACH_DIEUTRI
	AND NGAYTAO_CAC_CHITIET_DIEUTRI = @NGAYHOMNAY
	SET NOCOUNT OFF;
END

INSERT INTO CHITIET_DIEUTRI(ID_KEHOACH_DIEUTRI, ID_DIEUTRI, ID_RANG, LOAIMAT)
VALUES (10020, 1, 3, 'L'),
		(10020, 1, 4, 'L')

SELECT * FROM CHITIET_DIEUTRI
select * from KEHOACH_DIEUTRI
SELECT * FROM THONGTIN_THANHTOAN
