USE QLPHONGKHAM_CSDLNC1

DROP TRIGGER TRG_THEMCTDT_SINHRA_TTTHANHTOAN
DROP TRIGGER TRG_TONGTIENCHUATHANHTOAN_BN
DROP TRIGGER TRG_TONGTIENCHUATHANHTOAN_BN_DT
DROP TRIGGER TRG_TONGTIENTHANHTOANBENHNHAN
DROP TRIGGER TRG_TONGTIENTHANHTOANBENHNHAN_DT
-- CHI TIẾT ĐIỀU TRỊ SẼ TỰ ĐỘNG SINH RA TT THANH TOÁN
GO
DROP TRIGGER TRG_THEMCTDT_SINHRA_TTTHANHTOAN
GO
CREATE OR ALTER TRIGGER TRG_THEMCTDT_SINHRA_TTTHANHTOAN ON CHITIET_DIEUTRI AFTER INSERT AS 
BEGIN
	DECLARE @ID INT
	DECLARE @NGAYTAO DATE
	DECLARE @TONGTIENTHANHTOAN BIGINT
	SET @TONGTIENTHANHTOAN= (SELECT DT.PHI FROM DIEUTRI DT, INSERTED I WHERE I.ID_DIEUTRI=DT.ID_DIEUTRI )
	SET @ID =(SELECT I.ID_KEHOACH_DIEUTRI FROM INSERTED I)
	SET @NGAYTAO =(SELECT I.NGAYTAO FROM INSERTED I)
	INSERT THONGTIN_THANHTOAN (NGAYTAO_CAC_CHITIET_DIEUTRI,ID_KEHOACH_DIEUTRI,TONGTIENTHANHTOAN)
	VALUES(@NGAYTAO, @ID,@TONGTIENTHANHTOAN)
END 
-- TỔNG TIỀN CHƯA THANH TOÁN
GO
CREATE OR ALTER TRIGGER TRG_TONGTIENCHUATHANHTOAN_BN ON THONGTIN_THANHTOAN AFTER INSERT,UPDATE AS
BEGIN
	DECLARE @ID_BN INT
	DECLARE @TONGTIENTHUOC_CHUATHANHTOAN BIGINT
	DECLARE @TONGTIEN_DT_CHUATHANHTOAN BIGINT

	SET @ID_BN =(SELECT KHDT.ID_BENHNHAN FROM KEHOACH_DIEUTRI KHDT, inserted I WHERE I.ID_KEHOACH_DIEUTRI=KHDT.ID_KEHOACH_DIEUTRI)

	SET @TONGTIEN_DT_CHUATHANHTOAN=
	((SELECT SUM(TTTT.TONGTIENTHANHTOAN) FROM THONGTIN_THANHTOAN TTTT WHERE 
	TTTT.ID_KEHOACH_DIEUTRI= (SELECT ID_KEHOACH_DIEUTRI FROM KEHOACH_DIEUTRI WHERE ID_BENHNHAN=@ID_BN)) 
	- 
	(SELECT SUM(TTTT.TIENDATRA) FROM THONGTIN_THANHTOAN TTTT WHERE 
	TTTT.ID_KEHOACH_DIEUTRI= (SELECT ID_KEHOACH_DIEUTRI FROM KEHOACH_DIEUTRI WHERE ID_BENHNHAN=@ID_BN)))


	SET @TONGTIENTHUOC_CHUATHANHTOAN=
	((SELECT SUM (TTDT.TONGTIENTHANHTOAN) FROM THONGTIN_THANHTOAN_DONTHUOC TTDT WHERE 
	TTDT.ID_DONTHUOC=(SELECT ID_DONTHUOC FROM DONTHUOC DT WHERE DT.ID_BENHNHAN=@ID_BN))
	- (SELECT SUM (TTDT.TIENDATRA) FROM THONGTIN_THANHTOAN_DONTHUOC TTDT WHERE 
	TTDT.ID_DONTHUOC=(SELECT ID_DONTHUOC FROM DONTHUOC DT WHERE DT.ID_BENHNHAN=@ID_BN)))

	IF (@TONGTIEN_DT_CHUATHANHTOAN<0)
	BEGIN
		SET @TONGTIEN_DT_CHUATHANHTOAN=0
	END
	IF (@TONGTIENTHUOC_CHUATHANHTOAN<0)
	BEGIN
		 SET @TONGTIENTHUOC_CHUATHANHTOAN=0
	END
	
	UPDATE BENHNHAN 
	SET TONGTIENCHUATHANHTOAN=@TONGTIEN_DT_CHUATHANHTOAN+@TONGTIENTHUOC_CHUATHANHTOAN
	WHERE @ID_BN=ID_BENHNHAN
END 

GO
CREATE OR ALTER TRIGGER TRG_TONGTIENCHUATHANHTOAN_BN_DT ON THONGTIN_THANHTOAN_DONTHUOC AFTER INSERT,UPDATE AS
BEGIN
	DECLARE @ID_BN INT
	DECLARE @TONGTIENTHUOC_CHUATHANHTOAN BIGINT
	DECLARE @TONGTIEN_DT_CHUATHANHTOAN BIGINT

	SET @ID_BN =(SELECT DT.ID_BENHNHAN FROM DONTHUOC DT, inserted I WHERE I.ID_DONTHUOC=DT.ID_DONTHUOC)

	SET @TONGTIEN_DT_CHUATHANHTOAN=
	((SELECT SUM(TTTT.TONGTIENTHANHTOAN) FROM THONGTIN_THANHTOAN TTTT WHERE 
	TTTT.ID_KEHOACH_DIEUTRI= (SELECT ID_KEHOACH_DIEUTRI FROM KEHOACH_DIEUTRI WHERE ID_BENHNHAN=@ID_BN)) 
	- 
	(SELECT SUM(TTTT.TIENDATRA) FROM THONGTIN_THANHTOAN TTTT WHERE 
	TTTT.ID_KEHOACH_DIEUTRI= (SELECT ID_KEHOACH_DIEUTRI FROM KEHOACH_DIEUTRI WHERE ID_BENHNHAN=@ID_BN)))


	SET @TONGTIENTHUOC_CHUATHANHTOAN=
	((SELECT SUM (TTDT.TONGTIENTHANHTOAN) FROM THONGTIN_THANHTOAN_DONTHUOC TTDT WHERE 
	TTDT.ID_DONTHUOC=(SELECT ID_DONTHUOC FROM DONTHUOC DT WHERE DT.ID_BENHNHAN=@ID_BN))
	- (SELECT SUM (TTDT.TIENDATRA) FROM THONGTIN_THANHTOAN_DONTHUOC TTDT WHERE 
	TTDT.ID_DONTHUOC=(SELECT ID_DONTHUOC FROM DONTHUOC DT WHERE DT.ID_BENHNHAN=@ID_BN)))

	IF (@TONGTIEN_DT_CHUATHANHTOAN<0)
	BEGIN
		SET @TONGTIEN_DT_CHUATHANHTOAN=0
	END
	IF (@TONGTIENTHUOC_CHUATHANHTOAN<0)
	BEGIN
		 SET @TONGTIENTHUOC_CHUATHANHTOAN=0
	END
	
	UPDATE BENHNHAN 
	SET TONGTIENCHUATHANHTOAN=@TONGTIEN_DT_CHUATHANHTOAN+@TONGTIENTHUOC_CHUATHANHTOAN
	WHERE @ID_BN=ID_BENHNHAN
END 

-- TỔNG TIỀN THANH TOÁN CỦA BỆNH NHÂN 

GO 
CREATE OR ALTER TRIGGER TRG_TONGTIENTHANHTOANBENHNHAN ON THONGTIN_THANHTOAN AFTER INSERT,UPDATE AS
BEGIN
	DECLARE @ID_BN INT
	SET @ID_BN =(SELECT KHDT.ID_BENHNHAN FROM KEHOACH_DIEUTRI KHDT, inserted I WHERE I.ID_KEHOACH_DIEUTRI=KHDT.ID_KEHOACH_DIEUTRI)
	DECLARE @TONGTIEN_DT_THANHTOAN BIGINT
	DECLARE @TONGTIENTHUOC_THANHTOAN BIGINT

	SET @TONGTIEN_DT_THANHTOAN=
	(SELECT SUM(TTTT.TONGTIENTHANHTOAN) FROM THONGTIN_THANHTOAN TTTT WHERE 
	TTTT.ID_KEHOACH_DIEUTRI= (SELECT ID_KEHOACH_DIEUTRI FROM KEHOACH_DIEUTRI WHERE ID_BENHNHAN=@ID_BN))

	SET @TONGTIENTHUOC_THANHTOAN=
	(SELECT SUM (TTDT.TONGTIENTHANHTOAN) FROM THONGTIN_THANHTOAN_DONTHUOC TTDT WHERE 
	TTDT.ID_DONTHUOC=(SELECT ID_DONTHUOC FROM DONTHUOC DT WHERE DT.ID_BENHNHAN=@ID_BN))

	UPDATE BENHNHAN
	SET TONGTIENTHANHTOAN=@TONGTIEN_DT_THANHTOAN+@TONGTIENTHUOC_THANHTOAN
	WHERE @ID_BN=ID_BENHNHAN
END 


GO 
CREATE OR ALTER TRIGGER TRG_TONGTIENTHANHTOANBENHNHAN_DT ON THONGTIN_THANHTOAN_DONTHUOC AFTER INSERT,UPDATE AS
BEGIN
	DECLARE @ID_BN INT
	SET @ID_BN =(SELECT DT.ID_BENHNHAN FROM DONTHUOC DT, inserted I WHERE I.ID_DONTHUOC=DT.ID_DONTHUOC)
	DECLARE @TONGTIEN_DT_THANHTOAN BIGINT
	DECLARE @TONGTIENTHUOC_THANHTOAN BIGINT

	SET @TONGTIEN_DT_THANHTOAN=
	(SELECT SUM(TTTT.TONGTIENTHANHTOAN) FROM THONGTIN_THANHTOAN TTTT WHERE 
	TTTT.ID_KEHOACH_DIEUTRI= (SELECT ID_KEHOACH_DIEUTRI FROM KEHOACH_DIEUTRI WHERE ID_BENHNHAN=@ID_BN))

	SET @TONGTIENTHUOC_THANHTOAN=
	(SELECT SUM (TTDT.TONGTIENTHANHTOAN) FROM THONGTIN_THANHTOAN_DONTHUOC TTDT WHERE 
	TTDT.ID_DONTHUOC=(SELECT ID_DONTHUOC FROM DONTHUOC DT WHERE DT.ID_BENHNHAN=@ID_BN))

	UPDATE BENHNHAN
	SET TONGTIENTHANHTOAN=@TONGTIEN_DT_THANHTOAN+@TONGTIENTHUOC_THANHTOAN
	WHERE @ID_BN=ID_BENHNHAN
END 

