USE master;
GO

--CREATE OR ALTER TRIGGER TRIGGER_LICHLAMVIEC_GIOKETTHUC
--ON LICHLAMVIEC
--AFTER INSERT
--AS
--BEGIN
--    SET NOCOUNT ON;

--    UPDATE LICHLAMVIEC
--    SET GIOKETTHUC = DATEADD(HOUR, 4, i.GIOBATDAU)
--    FROM INSERTED i
--    WHERE LICHLAMVIEC.ID_LICHLAMVIEC = i.ID_LICHLAMVIEC;
--END;
--GO


INSERT INTO LICHLAMVIEC(ID_NHANVIEN, ID_PHONGKHAM, GIOBATDAU)
VALUES (3, 1, '2023-12-03 08:00')